// This file was auto-generated by Fern from our API Definition.

export const EventGetV1ResponseEventType = {
    PatientCreated: "patient.created",
    PatientUpdated: "patient.updated",
    ServiceCreated: "service.created",
    ServiceUpdated: "service.updated",
    PaymentCreated: "payment.created",
    PolicyCreated: "policy.created",
    PolicyUpdated: "policy.updated",
    NoteCreated: "note.created",
    NoteUpdated: "note.updated",
    ServiceEligibilityCreated: "service_eligibility.created",
    ServiceEligibilityUpdated: "service_eligibility.updated",
    ProviderEnrollmentStatusUpdated: "provider.enrollment_status.updated",
    EstimateChargeCreated: "estimate_charge.created",
    EstimateChargeUpdated: "estimate_charge.updated",
    ServiceInvoiceCreated: "service_invoice.created",
    ServiceInvoiceUpdated: "service_invoice.updated",
    FeeCreated: "fee.created",
    FeeUpdated: "fee.updated",
    PayerGroupHealthUpdated: "payer_group.health.updated",
    PayerGroupHealthEventCreated: "payer_group.health_event.created",
} as const;
export type EventGetV1ResponseEventType =
    (typeof EventGetV1ResponseEventType)[keyof typeof EventGetV1ResponseEventType];
