// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface EventsListV1ResponseItem {
    apiVersion: string;
    eventId: string;
    createdAt: string;
    eventType: BridgeApi.EventsListV1ResponseItemEventType;
    objectType: string;
    objectId: string;
    data?: unknown;
    previous?: unknown;
}
