// This file was auto-generated by Fern from our API Definition.

export const EventsListV1OrderCreatedAt = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type EventsListV1OrderCreatedAt = (typeof EventsListV1OrderCreatedAt)[keyof typeof EventsListV1OrderCreatedAt];
