/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface EventsListV1Response {
    apiVersion: string;
    eventId: string;
    createdAt: string;
    eventType: BridgeApi.EventsListV1ResponseEventType;
    objectType: string;
    objectId: string;
    data?: unknown;
    previous?: unknown;
}
