/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PolicyCreateV1RequestPerson {
    firstName: string;
    middleName?: string;
    lastName: string;
    /** Date, in the Patient's timezone, expressed as YYYY-MM-DD */
    dateOfBirth: string;
}
