/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PolicyGetV1ResponseRelationship = "SELF" | "CHILD" | "SPOUSE" | "OTHER" | "NONE";
export const PolicyGetV1ResponseRelationship = {
    Self: "SELF",
    Child: "CHILD",
    Spouse: "SPOUSE",
    Other: "OTHER",
    None: "NONE",
} as const;
