// This file was auto-generated by Fern from our API Definition.

export interface PolicyStreamV1ResponsePerson {
    firstName: string;
    middleName?: string;
    lastName: string;
    dateOfBirth?: string;
}
