// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface PolicyStreamV1Response {
    id: string;
    payerId: string;
    planName?: string;
    payer: BridgeApi.PolicyStreamV1ResponsePayer;
    person?: BridgeApi.PolicyStreamV1ResponsePerson;
    status: BridgeApi.PolicyStreamV1ResponseStatus;
    errors?: BridgeApi.PolicyStreamV1ResponseError[];
    memberId?: string;
    policyHolder?: BridgeApi.PolicyStreamV1ResponsePolicyHolder;
    relationship?: BridgeApi.PolicyStreamV1ResponseRelationship;
    state: BridgeApi.PolicyStreamV1ResponseState;
    patientId?: string;
    latest?: BridgeApi.PolicyStreamV1ResponseLatest;
}
