/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PolicyGetV1ResponseLatest {
    id: string;
    plan: string;
    /** Timestamp this was executed */
    validatedAt: string;
    effectiveFrom?: string;
    effectiveTo?: string;
}
