// This file was auto-generated by Fern from our API Definition.

export const PolicyGetV1ResponseStatus = {
    Pending: "PENDING",
    Unknown: "UNKNOWN",
    Confirmed: "CONFIRMED",
    Revalidating: "REVALIDATING",
    Invalid: "INVALID",
} as const;
export type PolicyGetV1ResponseStatus = (typeof PolicyGetV1ResponseStatus)[keyof typeof PolicyGetV1ResponseStatus];
