/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PolicyCreateV1ResponsePayer {
    id: string;
    code: string;
    name: string;
    memberId: boolean;
    hint?: string;
}
