// This file was auto-generated by Fern from our API Definition.

export const PolicyStreamV1ResponseStatus = {
    Pending: "PENDING",
    Unknown: "UNKNOWN",
    Confirmed: "CONFIRMED",
    Revalidating: "REVALIDATING",
    Invalid: "INVALID",
} as const;
export type PolicyStreamV1ResponseStatus =
    (typeof PolicyStreamV1ResponseStatus)[keyof typeof PolicyStreamV1ResponseStatus];
