/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PolicyCreateV1Response {
    id: string;
    payerId: string;
    planName?: string;
    payer: BridgeApi.PolicyCreateV1ResponsePayer;
    person?: BridgeApi.PolicyCreateV1ResponsePerson;
    status: BridgeApi.PolicyCreateV1ResponseStatus;
    errors?: BridgeApi.PolicyCreateV1ResponseError[];
    memberId?: string;
    policyHolder?: BridgeApi.PolicyCreateV1ResponsePolicyHolder;
    relationship?: BridgeApi.PolicyCreateV1ResponseRelationship;
    state: BridgeApi.PolicyCreateV1ResponseState;
    patientId?: string;
    latest?: BridgeApi.PolicyCreateV1ResponseLatest;
}
