/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PolicyCreateV1ResponseStatus = "PENDING" | "UNKNOWN" | "CONFIRMED" | "REVALIDATING" | "INVALID";
export const PolicyCreateV1ResponseStatus = {
    Pending: "PENDING",
    Unknown: "UNKNOWN",
    Confirmed: "CONFIRMED",
    Revalidating: "REVALIDATING",
    Invalid: "INVALID",
} as const;
