// This file was auto-generated by Fern from our API Definition.

export const PolicyStreamV1ResponseRelationship = {
    Self: "SELF",
    Child: "CHILD",
    Spouse: "SPOUSE",
    Other: "OTHER",
    None: "NONE",
} as const;
export type PolicyStreamV1ResponseRelationship =
    (typeof PolicyStreamV1ResponseRelationship)[keyof typeof PolicyStreamV1ResponseRelationship];
