// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ProviderGetV1Response {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.ProviderGetV1ResponseType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
