// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ProviderPostV1Request {
    providers: BridgeApi.ProviderPostV1RequestProvider[];
}
