// This file was auto-generated by Fern from our API Definition.

export const ProviderGetV1ResponseType = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
} as const;
export type ProviderGetV1ResponseType = (typeof ProviderGetV1ResponseType)[keyof typeof ProviderGetV1ResponseType];
