// This file was auto-generated by Fern from our API Definition.

export const ProvidersListV1ResponseItemType = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
    Pt: "PT",
} as const;
export type ProvidersListV1ResponseItemType =
    (typeof ProvidersListV1ResponseItemType)[keyof typeof ProvidersListV1ResponseItemType];
