// This file was auto-generated by Fern from our API Definition.

export const ProviderPostV1ResponseSuccessfulElementProviderType = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Lmft: "LMFT",
    Lpc: "LPC",
    Psych: "PSYCH",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
    Pt: "PT",
} as const;
export type ProviderPostV1ResponseSuccessfulElementProviderType =
    (typeof ProviderPostV1ResponseSuccessfulElementProviderType)[keyof typeof ProviderPostV1ResponseSuccessfulElementProviderType];
