// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ProviderSubmitV1ResponseFailed {
    caqhId: string;
    credential?: string;
    email: string;
    error?: string;
    externalId?: string;
    firstName?: string;
    lastName?: string;
    npi: string;
    providerType?: BridgeApi.ProviderSubmitV1ResponseFailedElementProviderType;
}
