// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ProvidersListV1Response {
    /** List results */
    items: BridgeApi.ProvidersListV1ResponseItem[];
    /** Total count (if available) */
    count?: number;
}
