// This file was auto-generated by Fern from our API Definition.

export interface ProviderPostV1RequestProvider {
    npi: string;
    email: string;
    caqhId: string;
    caqhUsername: string;
    caqhPassword: string;
    externalId?: string;
}
