// This file was auto-generated by Fern from our API Definition.

export const SubmitProviderPostV1ResponseSuccessfulElementProviderType = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
    Pt: "PT",
} as const;
export type SubmitProviderPostV1ResponseSuccessfulElementProviderType =
    (typeof SubmitProviderPostV1ResponseSuccessfulElementProviderType)[keyof typeof SubmitProviderPostV1ResponseSuccessfulElementProviderType];
