// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface SubmitProviderPostV1Request {
    providers: BridgeApi.SubmitProviderPostV1RequestProvider[];
}
