// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface SubmitProviderPostV1ResponseSubmit {
    caqhId: string;
    credential?: string;
    email: string;
    externalId?: string;
    firstName: string;
    lastName: string;
    npi: string;
    providerId: string;
    providerType: BridgeApi.SubmitProviderPostV1ResponseSubmitElementProviderType;
}
