// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface SubmitProviderPostV1Response {
    failed: BridgeApi.SubmitProviderPostV1ResponseFailed[];
    successful: BridgeApi.SubmitProviderPostV1ResponseSuccessful[];
}
