// This file was auto-generated by Fern from our API Definition.

export type ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementConditionsElementDiagnosis =
    string;
