// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
export type ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric =
    (typeof ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric)[keyof typeof ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric];
