// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseStatus = {
    Pending: "PENDING",
    Billing: "BILLING",
    Settling: "SETTLING",
    Complete: "COMPLETE",
    Triage: "TRIAGE",
    Canceled: "CANCELED",
    Denied: "DENIED",
} as const;
export type ServiceCreateV2ResponseStatus =
    (typeof ServiceCreateV2ResponseStatus)[keyof typeof ServiceCreateV2ResponseStatus];
