// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceCancelV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType =
    (typeof ServiceCancelV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType)[keyof typeof ServiceCancelV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType];
