/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV2ResponseTasksElementType =
    | "PATIENT_CONSENT"
    | "PATIENT_INSURANCE"
    | "PATIENT_ADDRESS"
    | "DATE_OF_SERVICE"
    | "DUPLICATE_SERVICE_TYPE"
    | "INVALID_INITIAL_SERVICE_TYPE"
    | "REPLACE_NOTE"
    | "UPDATE_NOTE"
    | "TRIAGE"
    | "COVERAGE"
    | "PRIOR_AUTHORIZATION"
    | "BILLING_TIME_LIMIT"
    | "PROVIDER_NOT_ENROLLED"
    | "THERAPY_DURATION"
    | "MINIMUM_DURATION"
    | "MISSING_TIME_SPENT_MINUTES"
    | "PATIENT_CONSENT_EXPIRED"
    | "INVALID_DATE_RANGE"
    | "INSUFFICIENT_MONITORING_DATA";
export const ServiceCancelV2ResponseTasksElementType = {
    PatientConsent: "PATIENT_CONSENT",
    PatientInsurance: "PATIENT_INSURANCE",
    PatientAddress: "PATIENT_ADDRESS",
    DateOfService: "DATE_OF_SERVICE",
    DuplicateServiceType: "DUPLICATE_SERVICE_TYPE",
    InvalidInitialServiceType: "INVALID_INITIAL_SERVICE_TYPE",
    ReplaceNote: "REPLACE_NOTE",
    UpdateNote: "UPDATE_NOTE",
    Triage: "TRIAGE",
    Coverage: "COVERAGE",
    PriorAuthorization: "PRIOR_AUTHORIZATION",
    BillingTimeLimit: "BILLING_TIME_LIMIT",
    ProviderNotEnrolled: "PROVIDER_NOT_ENROLLED",
    TherapyDuration: "THERAPY_DURATION",
    MinimumDuration: "MINIMUM_DURATION",
    MissingTimeSpentMinutes: "MISSING_TIME_SPENT_MINUTES",
    PatientConsentExpired: "PATIENT_CONSENT_EXPIRED",
    InvalidDateRange: "INVALID_DATE_RANGE",
    InsufficientMonitoringData: "INSUFFICIENT_MONITORING_DATA",
} as const;
