// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2RequestResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceCreateV2RequestResponsibleParty =
    (typeof ServiceCreateV2RequestResponsibleParty)[keyof typeof ServiceCreateV2RequestResponsibleParty];
