/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibility {
    conditions: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility;
}
