/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicesListV2ResponsePatientResponsibilityFieldStatus = "UNKNOWN" | "ESTIMATE" | "FINALIZED";
export const ServicesListV2ResponsePatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
