// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2ResponseServiceEligibilityFieldProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibilityFieldProvidersElementType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
