// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2ResponseServiceEligibilityFieldClinicalInfo {
    diagnoses?: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibilityFieldClinicalInfoFieldDiagnosis[];
}
