// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponseServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
export type ServiceUpdateV2ResponseServiceTypeFieldPlaceOfService =
    (typeof ServiceUpdateV2ResponseServiceTypeFieldPlaceOfService)[keyof typeof ServiceUpdateV2ResponseServiceTypeFieldPlaceOfService];
