// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCancelV2ResponseTask {
    type: BridgeApi.services.ServiceCancelV2ResponseTasksElementType;
    memo?: string;
}
