/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV2ResponseClaimStatus = "CREATED" | "IN_PROGRESS" | "PAID" | "DENIED";
export const ServiceCancelV2ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
