/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServicesListV2ResponseServiceType {
    id: string;
    name: string;
    placeOfService: BridgeApi.services.ServicesListV2ResponseServiceTypeFieldPlaceOfService;
    /** [DEPRECATED] The first supported ProviderType, see new 'providerType' array */
    providerType: BridgeApi.services.ServicesListV2ResponseServiceTypeFieldProviderType;
    /** All supported ProviderTypes */
    providerTypes: BridgeApi.services.ServicesListV2ResponseServiceTypeFieldProviderType[];
    cost: number;
    noteFields: BridgeApi.services.ServicesListV2ResponseServiceTypeFieldNoteField[];
    conditionalPatientResponsibility: boolean;
    selfPayCost?: number;
}
