// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2ResponsePayment {
    id: string;
    createdAt: string;
    serviceId: string;
    paidAt: string;
    transactionId: string;
    type: BridgeApi.services.ServiceUpdateV2ResponsePaymentsElementType;
    amount: number;
    externalId?: string;
    memo?: string;
}
