/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2Request {
    patientId: string;
    /** Full ISO8601 timestamp, including timezone */
    dateOfService: string;
    serviceTypeId: string;
    externalId?: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.services.ServiceCreateV2RequestLocation;
    providerId: string;
    serviceEligibility?: BridgeApi.services.ServiceCreateV2RequestServiceEligibility;
    priorAuthorizationNumber?: string;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.services.ServiceCreateV2RequestMetadata;
    responsibleParty?: BridgeApi.services.ServiceCreateV2RequestResponsibleParty;
}
