/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV2RequestLocationFieldCountry = "US";
export const ServiceCreateV2RequestLocationFieldCountry = {
    Us: "US",
} as const;
