/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV2ResponseLocationFieldCountry = "US";
export const ServiceCancelV2ResponseLocationFieldCountry = {
    Us: "US",
} as const;
