/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV2ResponsePaymentsElementType = "PATIENT" | "ADJUSTMENT";
export const ServiceCreateV2ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
