// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
export type ServiceCreateV2ResponseServiceTypeFieldPlaceOfService =
    (typeof ServiceCreateV2ResponseServiceTypeFieldPlaceOfService)[keyof typeof ServiceCreateV2ResponseServiceTypeFieldPlaceOfService];
