/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV2ResponseServiceTypeFieldPlaceOfService =
    | "TELEHEALTH_HOME"
    | "TELEHEALTH_NOT_HOME"
    | "OFFICE";
export const ServiceCreateV2ResponseServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
