/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV2ResponseResponsibleParty = "PATIENT" | "INSURANCE";
export const ServiceCreateV2ResponseResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
