// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
export type ServiceCancelV2ResponseClaimStatus =
    (typeof ServiceCancelV2ResponseClaimStatus)[keyof typeof ServiceCancelV2ResponseClaimStatus];
