// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceCreateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType =
    (typeof ServiceCreateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceCreateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType];
