// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
export type ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod];
