// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponsePatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
export type ServiceUpdateV2ResponsePatientResponsibilityFieldStatus =
    (typeof ServiceUpdateV2ResponsePatientResponsibilityFieldStatus)[keyof typeof ServiceUpdateV2ResponsePatientResponsibilityFieldStatus];
