// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponseServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
export type ServiceCancelV2ResponseServiceTypeFieldPlaceOfService =
    (typeof ServiceCancelV2ResponseServiceTypeFieldPlaceOfService)[keyof typeof ServiceCancelV2ResponseServiceTypeFieldPlaceOfService];
