/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition {
    diagnoses?: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementConditionsElementDiagnosis[];
}
