/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    | "UNKNOWN"
    | "UNLIMITED"
    | "LIMITED";
export const ServiceCancelV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
