// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponseServiceEligibilityFieldStatus = {
    Pending: "PENDING",
    Uninsured: "UNINSURED",
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
    Ineffective: "INEFFECTIVE",
} as const;
export type ServiceCancelV2ResponseServiceEligibilityFieldStatus =
    (typeof ServiceCancelV2ResponseServiceEligibilityFieldStatus)[keyof typeof ServiceCancelV2ResponseServiceEligibilityFieldStatus];
