// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponseStatus = {
    Pending: "PENDING",
    Billing: "BILLING",
    Settling: "SETTLING",
    Complete: "COMPLETE",
    Triage: "TRIAGE",
    Canceled: "CANCELED",
    Denied: "DENIED",
} as const;
export type ServiceCancelV2ResponseStatus =
    (typeof ServiceCancelV2ResponseStatus)[keyof typeof ServiceCancelV2ResponseStatus];
