/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export type ServicesListV2FilterStatus = BridgeApi.services.ServicesListV2FilterStatusElement;
