/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV2ResponseCancellationReason = "NO_SHOW";
export const ServiceCreateV2ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
