// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2Request {
    patientToken?: string;
    /** Full ISO8601 timestamp, including timezone */
    dateOfService?: string;
    serviceTypeId?: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location?: BridgeApi.services.ServiceUpdateV2RequestLocation;
    externalId?: string;
    providerId?: string;
    priorAuthorizationNumber?: string;
    responsibleParty?: BridgeApi.services.ServiceUpdateV2RequestResponsibleParty;
    /** Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value */
    metadata?: BridgeApi.services.ServiceUpdateV2RequestMetadata;
}
