// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
export type ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType];
