// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
export type ServiceCreateV2ResponseCancellationReason =
    (typeof ServiceCreateV2ResponseCancellationReason)[keyof typeof ServiceCreateV2ResponseCancellationReason];
