// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceCreateV2ResponseResponsibleParty =
    (typeof ServiceCreateV2ResponseResponsibleParty)[keyof typeof ServiceCreateV2ResponseResponsibleParty];
