// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceUpdateV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType =
    (typeof ServiceUpdateV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType)[keyof typeof ServiceUpdateV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType];
