/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServicesListV2ResponseServiceEligibility {
    id: string;
    organizationId: string;
    /** Timestamp this was executed */
    validatedAt?: string;
    serviceTypeId: string;
    dateOfService: string;
    status: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldStatus;
    patientResponsibility?: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldPatientResponsibility;
    providers: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldProvider[];
    policyIds: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldPolicyId[];
    state: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldState;
    messages?: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldMessage[];
    clinicalInfo?: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldClinicalInfo;
    conditionalPatientResponsibilities?: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibility[];
}
