// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2ResponseProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.services.ServiceUpdateV2ResponseProviderFieldType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
