// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceUpdateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType =
    (typeof ServiceUpdateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceUpdateV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType];
