/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType = "INDIVIDUAL" | "FAMILY";
export const ServiceCancelV2ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
