// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    {
        Individual: "INDIVIDUAL",
        Family: "FAMILY",
    } as const;
export type ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    (typeof ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType];
