/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServicesListV2ResponseServiceEligibilityFieldProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.services.ServicesListV2ResponseServiceEligibilityFieldProvidersElementType;
    providerEligibilityEnabled: boolean;
    serviceEligibilityEnabled: boolean;
    npi: string;
}
