/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit {
    type: BridgeApi.services.ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType;
    value?: number;
    metric?: BridgeApi.services.ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric;
    period?: BridgeApi.services.ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod;
    units?: BridgeApi.services.ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits;
}
