// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponseCoverageStatus = {
    Pending: "PENDING",
    Revalidating: "REVALIDATING",
    Valid: "VALID",
    InvalidCoverage: "INVALID_COVERAGE",
    InvalidProvider: "INVALID_PROVIDER",
} as const;
export type ServiceCancelV2ResponseCoverageStatus =
    (typeof ServiceCancelV2ResponseCoverageStatus)[keyof typeof ServiceCancelV2ResponseCoverageStatus];
