// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2Response {
    id: string;
    organizationId: string;
    status: BridgeApi.services.ServiceUpdateV2ResponseStatus;
    createdAt: string;
    serviceType: BridgeApi.services.ServiceUpdateV2ResponseServiceType;
    dateOfService: string;
    externalId?: string;
    patientId: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.services.ServiceUpdateV2ResponseLocation;
    noteId?: string;
    serviceEligibility: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibility;
    coverageStatus: BridgeApi.services.ServiceUpdateV2ResponseCoverageStatus;
    provider: BridgeApi.services.ServiceUpdateV2ResponseProvider;
    payments: BridgeApi.services.ServiceUpdateV2ResponsePayment[];
    responsibleParty: BridgeApi.services.ServiceUpdateV2ResponseResponsibleParty;
    patientResponsibility: BridgeApi.services.ServiceUpdateV2ResponsePatientResponsibility;
    tasks: BridgeApi.services.ServiceUpdateV2ResponseTask[];
    claimStatus?: BridgeApi.services.ServiceUpdateV2ResponseClaimStatus;
    priorAuthorizationNumber?: string;
    cancellationReason?: BridgeApi.services.ServiceUpdateV2ResponseCancellationReason;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.services.ServiceUpdateV2ResponseMetadata;
}
