// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCancelV2ResponseServiceEligibilityFieldClinicalInfo {
    diagnoses?: BridgeApi.services.ServiceCancelV2ResponseServiceEligibilityFieldClinicalInfoFieldDiagnosis[];
}
