// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export type ServiceCancelV2ResponseServiceTypeFieldProviderType =
    BridgeApi.services.ServiceCancelV2ResponseServiceTypeFieldProviderTypesElement;
