// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2ResponseLocation {
    line1?: string;
    line2?: string;
    city?: string;
    /** 2 letter US state code */
    state: BridgeApi.services.ServiceUpdateV2ResponseLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.services.ServiceUpdateV2ResponseLocationFieldCountry;
}
