/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCancelV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility {
    total: number;
    fallback: number;
    deductible: number;
    deductibleType?: BridgeApi.services.ServiceCancelV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType;
    coinsurance: number;
    coinsurancePercent: number;
    copayment: number;
    oopFallback: number;
    oopCopayment: number;
    oopCoinsurance: number;
    oopDeductible: number;
}
