// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2RequestServiceEligibilityFieldClinicalInfo {
    diagnoses?: BridgeApi.services.ServiceCreateV2RequestServiceEligibilityFieldClinicalInfoFieldDiagnosis[];
}
