// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseLocationFieldCountry = {
    Us: "US",
} as const;
export type ServiceCreateV2ResponseLocationFieldCountry =
    (typeof ServiceCreateV2ResponseLocationFieldCountry)[keyof typeof ServiceCreateV2ResponseLocationFieldCountry];
