// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponsePatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
export type ServiceCreateV2ResponsePatientResponsibilityFieldStatus =
    (typeof ServiceCreateV2ResponsePatientResponsibilityFieldStatus)[keyof typeof ServiceCreateV2ResponsePatientResponsibilityFieldStatus];
