// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCancelV2Response {
    id: string;
    organizationId: string;
    status: BridgeApi.services.ServiceCancelV2ResponseStatus;
    createdAt: string;
    serviceType: BridgeApi.services.ServiceCancelV2ResponseServiceType;
    dateOfService: string;
    externalId?: string;
    patientId: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.services.ServiceCancelV2ResponseLocation;
    noteId?: string;
    serviceEligibility: BridgeApi.services.ServiceCancelV2ResponseServiceEligibility;
    coverageStatus: BridgeApi.services.ServiceCancelV2ResponseCoverageStatus;
    provider: BridgeApi.services.ServiceCancelV2ResponseProvider;
    payments: BridgeApi.services.ServiceCancelV2ResponsePayment[];
    responsibleParty: BridgeApi.services.ServiceCancelV2ResponseResponsibleParty;
    patientResponsibility: BridgeApi.services.ServiceCancelV2ResponsePatientResponsibility;
    tasks: BridgeApi.services.ServiceCancelV2ResponseTask[];
    claimStatus?: BridgeApi.services.ServiceCancelV2ResponseClaimStatus;
    priorAuthorizationNumber?: string;
    cancellationReason?: BridgeApi.services.ServiceCancelV2ResponseCancellationReason;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.services.ServiceCancelV2ResponseMetadata;
}
