// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility {
    total: number;
    fallback: number;
    deductible: number;
    deductibleType?: BridgeApi.services.ServiceCreateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType;
    coinsurance: number;
    coinsurancePercent: number;
    copayment: number;
    oopFallback: number;
    oopCopayment: number;
    oopCoinsurance: number;
    oopDeductible: number;
}
