/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2RequestLocation {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.services.ServiceCreateV2RequestLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.services.ServiceCreateV2RequestLocationFieldCountry;
}
