// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2Response {
    id: string;
    organizationId: string;
    status: BridgeApi.services.ServiceCreateV2ResponseStatus;
    createdAt: string;
    serviceType: BridgeApi.services.ServiceCreateV2ResponseServiceType;
    dateOfService: string;
    externalId?: string;
    patientId: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.services.ServiceCreateV2ResponseLocation;
    noteId?: string;
    serviceEligibility: BridgeApi.services.ServiceCreateV2ResponseServiceEligibility;
    coverageStatus: BridgeApi.services.ServiceCreateV2ResponseCoverageStatus;
    provider: BridgeApi.services.ServiceCreateV2ResponseProvider;
    payments: BridgeApi.services.ServiceCreateV2ResponsePayment[];
    responsibleParty: BridgeApi.services.ServiceCreateV2ResponseResponsibleParty;
    patientResponsibility: BridgeApi.services.ServiceCreateV2ResponsePatientResponsibility;
    tasks: BridgeApi.services.ServiceCreateV2ResponseTask[];
    claimStatus?: BridgeApi.services.ServiceCreateV2ResponseClaimStatus;
    priorAuthorizationNumber?: string;
    cancellationReason?: BridgeApi.services.ServiceCreateV2ResponseCancellationReason;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.services.ServiceCreateV2ResponseMetadata;
}
