// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2RequestLocationFieldCountry = {
    Us: "US",
} as const;
export type ServiceCreateV2RequestLocationFieldCountry =
    (typeof ServiceCreateV2RequestLocationFieldCountry)[keyof typeof ServiceCreateV2RequestLocationFieldCountry];
