// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type ServiceUpdateV2ResponsePaymentsElementType =
    (typeof ServiceUpdateV2ResponsePaymentsElementType)[keyof typeof ServiceUpdateV2ResponsePaymentsElementType];
