// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV2ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
export type ServiceCreateV2ResponseClaimStatus =
    (typeof ServiceCreateV2ResponseClaimStatus)[keyof typeof ServiceCreateV2ResponseClaimStatus];
