// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit {
    type: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType;
    value?: number;
    metric?: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric;
    period?: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod;
    units?: BridgeApi.services.ServiceUpdateV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits;
}
