/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServicesListV2ResponseLocation {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.services.ServicesListV2ResponseLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.services.ServicesListV2ResponseLocationFieldCountry;
}
