/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV2RequestResponsibleParty = "PATIENT" | "INSURANCE";
export const ServiceCreateV2RequestResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
