// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
export type ServiceUpdateV2ResponseClaimStatus =
    (typeof ServiceUpdateV2ResponseClaimStatus)[keyof typeof ServiceUpdateV2ResponseClaimStatus];
