/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicesListV2FilterStatusElement =
    | "PENDING"
    | "BILLING"
    | "SETTLING"
    | "COMPLETE"
    | "TRIAGE"
    | "CANCELED"
    | "DENIED";
export const ServicesListV2FilterStatusElement = {
    Pending: "PENDING",
    Billing: "BILLING",
    Settling: "SETTLING",
    Complete: "COMPLETE",
    Triage: "TRIAGE",
    Canceled: "CANCELED",
    Denied: "DENIED",
} as const;
