// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV2RequestResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceUpdateV2RequestResponsibleParty =
    (typeof ServiceUpdateV2RequestResponsibleParty)[keyof typeof ServiceUpdateV2RequestResponsibleParty];
