// This file was auto-generated by Fern from our API Definition.

export const ServiceCancelV2ResponseResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceCancelV2ResponseResponsibleParty =
    (typeof ServiceCancelV2ResponseResponsibleParty)[keyof typeof ServiceCancelV2ResponseResponsibleParty];
