/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric =
    | "VISIT"
    | "UNITS";
export const ServicesListV2ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
