// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceCreateV2RequestServiceEligibility {
    /** Extracts fields (clinicalInfo, etc.) from an existing ServiceEligibility */
    id?: string;
    clinicalInfo?: BridgeApi.services.ServiceCreateV2RequestServiceEligibilityFieldClinicalInfo;
}
