/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType =
    | "INDIVIDUAL"
    | "FAMILY";
export const ServiceCancelV2ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
