// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface PatientGetV2ResponseAddress {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.patients.PatientGetV2ResponseAddressFieldState;
    postalCode?: string;
    country?: BridgeApi.patients.PatientGetV2ResponseAddressFieldCountry;
}
