/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientUpdateV2ResponseAddressFieldCountry = "US";
export const PatientUpdateV2ResponseAddressFieldCountry = {
    Us: "US",
} as const;
