/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface PatientUpdateV2RequestAddress {
    line1: string;
    line2?: string;
    city: string;
    state: BridgeApi.patients.PatientUpdateV2RequestAddressFieldState;
    postalCode: string;
    country?: BridgeApi.patients.PatientUpdateV2RequestAddressFieldCountry;
}
