/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientCreateV2ResponseAccountFieldStatus = "CURRENT" | "DUE" | "DELINQUENT";
export const PatientCreateV2ResponseAccountFieldStatus = {
    Current: "CURRENT",
    Due: "DUE",
    Delinquent: "DELINQUENT",
} as const;
