// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface PatientGetV2ResponseAccount {
    status: BridgeApi.patients.PatientGetV2ResponseAccountFieldStatus;
    balance: number;
}
