// This file was auto-generated by Fern from our API Definition.

export const PatientCreateV2RequestAddressFieldCountry = {
    Us: "US",
} as const;
export type PatientCreateV2RequestAddressFieldCountry =
    (typeof PatientCreateV2RequestAddressFieldCountry)[keyof typeof PatientCreateV2RequestAddressFieldCountry];
