/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientCreateV2RequestAddressFieldCountry = "US";
export const PatientCreateV2RequestAddressFieldCountry = {
    Us: "US",
} as const;
