/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientCreateV2ResponseAddressFieldCountry = "US";
export const PatientCreateV2ResponseAddressFieldCountry = {
    Us: "US",
} as const;
