/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface PatientCreateV2Response {
    id: string;
    patientToken?: string;
    createdAt: string;
    externalId?: string;
    coverage: BridgeApi.patients.PatientCreateV2ResponseCoverage[];
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    email: string;
    phone?: string;
    address?: BridgeApi.patients.PatientCreateV2ResponseAddress;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.patients.PatientCreateV2ResponseMetadata;
    account?: BridgeApi.patients.PatientCreateV2ResponseAccount;
}
