// This file was auto-generated by Fern from our API Definition.

export const PatientGetV2ResponseAddressFieldCountry = {
    Us: "US",
} as const;
export type PatientGetV2ResponseAddressFieldCountry =
    (typeof PatientGetV2ResponseAddressFieldCountry)[keyof typeof PatientGetV2ResponseAddressFieldCountry];
