/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface PatientUpdateV2ResponseAccount {
    status: BridgeApi.patients.PatientUpdateV2ResponseAccountFieldStatus;
    balance: number;
}
