/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    | "ANNUAL"
    | "BENEFIT_YEAR"
    | "LIFETIME";
export const ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
