/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric =
    | "VISIT"
    | "UNITS";
export const ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
