// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibility {
    total: number;
    fallback: number;
    deductible: number;
    deductibleType?: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType;
    coinsurance: number;
    coinsurancePercent: number;
    copayment: number;
    oopFallback: number;
    oopCopayment: number;
    oopCoinsurance: number;
    oopDeductible: number;
}
