// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType =
    (typeof ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType)[keyof typeof ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType];
