/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityCreateV2ResponseStatus =
    | "PENDING"
    | "UNINSURED"
    | "ELIGIBLE"
    | "INELIGIBLE"
    | "INEFFECTIVE";
export const ServiceEligibilityCreateV2ResponseStatus = {
    Pending: "PENDING",
    Uninsured: "UNINSURED",
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
    Ineffective: "INEFFECTIVE",
} as const;
