// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceEligibilityCreateV2ResponseConditionalPatientResponsibility {
    conditions: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibility;
}
