/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType = "INDIVIDUAL" | "FAMILY";
export const ServiceEligibilityCreateV2ResponsePatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
