// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    {
        Individual: "INDIVIDUAL",
        Family: "FAMILY",
    } as const;
export type ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    (typeof ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType];
