// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServiceEligibilityCreateV2ResponseProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseProvidersElementType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
