/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../index.js";

export interface ServiceEligibilityCreateV2Response {
    id: string;
    organizationId: string;
    /** Timestamp this was executed */
    validatedAt?: string;
    serviceTypeId: string;
    dateOfService: string;
    status: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseStatus;
    patientResponsibility?: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponsePatientResponsibility;
    providers: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseProvider[];
    policyIds: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponsePolicyId[];
    state: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseState;
    messages?: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseMessage[];
    clinicalInfo?: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseClinicalInfo;
    conditionalPatientResponsibilities?: BridgeApi.serviceEligibility.ServiceEligibilityCreateV2ResponseConditionalPatientResponsibility[];
}
