/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ServiceEligibilityCreateV2ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits {
    /** Conversion rate from units to minutes */
    minutes: number;
    /** Minimum number of units */
    min: number;
    /** Maximum number of units */
    max: number;
}
