/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceUpdateV1RequestLocation {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.ServiceUpdateV1RequestLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.ServiceUpdateV1RequestLocationFieldCountry;
}
