// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseItemLocation {
    line1?: string;
    line2?: string;
    city?: string;
    /** 2 letter US state code */
    state: BridgeApi.ServicesListV1ResponseItemLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.ServicesListV1ResponseItemLocationFieldCountry;
}
