// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseTasksElementType = {
    PatientConsent: "PATIENT_CONSENT",
    PatientInsurance: "PATIENT_INSURANCE",
    PatientAddress: "PATIENT_ADDRESS",
    ServiceLocation: "SERVICE_LOCATION",
    DateOfService: "DATE_OF_SERVICE",
    DuplicateServiceType: "DUPLICATE_SERVICE_TYPE",
    InvalidInitialServiceType: "INVALID_INITIAL_SERVICE_TYPE",
    ReplaceNote: "REPLACE_NOTE",
    UpdateNote: "UPDATE_NOTE",
    Triage: "TRIAGE",
    Coverage: "COVERAGE",
    PriorAuthorization: "PRIOR_AUTHORIZATION",
    BillingTimeLimit: "BILLING_TIME_LIMIT",
    ProviderNotEnrolled: "PROVIDER_NOT_ENROLLED",
    TherapyDuration: "THERAPY_DURATION",
    MinimumDuration: "MINIMUM_DURATION",
    MissingInitiatingVisit: "MISSING_INITIATING_VISIT",
    MissingAssessment: "MISSING_ASSESSMENT",
    MissingTimeSpentMinutes: "MISSING_TIME_SPENT_MINUTES",
    PatientConsentExpired: "PATIENT_CONSENT_EXPIRED",
    InvalidDateRange: "INVALID_DATE_RANGE",
    InsufficientMonitoringData: "INSUFFICIENT_MONITORING_DATA",
    MismatchedIcd10: "MISMATCHED_ICD10",
    BillingFrequencyLimit: "BILLING_FREQUENCY_LIMIT",
    PatientReconsent: "PATIENT_RECONSENT",
    ProviderChanged: "PROVIDER_CHANGED",
} as const;
export type ServiceStreamV1ResponseTasksElementType =
    (typeof ServiceStreamV1ResponseTasksElementType)[keyof typeof ServiceStreamV1ResponseTasksElementType];
