// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
export type ServicesListV1ResponseItemServiceTypeFieldPlaceOfService =
    (typeof ServicesListV1ResponseItemServiceTypeFieldPlaceOfService)[keyof typeof ServicesListV1ResponseItemServiceTypeFieldPlaceOfService];
