/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceGetV1ResponseServiceEligibility {
    id: string;
    organizationId: string;
    /** Timestamp this was executed */
    validatedAt?: string;
    serviceTypeId: string;
    dateOfService: string;
    status: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldStatus;
    patientResponsibility?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldPatientResponsibility;
    providers: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldProvider[];
    policyIds: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldPolicyId[];
    state: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldState;
    messages?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldMessage[];
    clinicalInfo?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldClinicalInfo;
    conditionalPatientResponsibilities?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibility[];
}
