/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceGetV1ResponseServiceEligibilityFieldClinicalInfo {
    diagnoses?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldClinicalInfoFieldDiagnosis[];
}
