// This file was auto-generated by Fern from our API Definition.

export const ServiceGetV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceGetV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType =
    (typeof ServiceGetV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType)[keyof typeof ServiceGetV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType];
