// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServicesListV1ResponseItemServiceEligibilityFieldPatientResponsibilityFieldDeductibleType =
    (typeof ServicesListV1ResponseItemServiceEligibilityFieldPatientResponsibilityFieldDeductibleType)[keyof typeof ServicesListV1ResponseItemServiceEligibilityFieldPatientResponsibilityFieldDeductibleType];
