// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type ServiceCreateV1ResponsePaymentsElementType =
    (typeof ServiceCreateV1ResponsePaymentsElementType)[keyof typeof ServiceCreateV1ResponsePaymentsElementType];
