// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemPatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
export type ServicesListV1ResponseItemPatientResponsibilityFieldStatus =
    (typeof ServicesListV1ResponseItemPatientResponsibilityFieldStatus)[keyof typeof ServicesListV1ResponseItemPatientResponsibilityFieldStatus];
