/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceStreamV1ResponsePaymentsElementType = "PATIENT" | "ADJUSTMENT";
export const ServiceStreamV1ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
