// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
export type ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType];
