// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1Response {
    id: string;
    organizationId: string;
    status: BridgeApi.ServiceCreateV1ResponseStatus;
    createdAt: string;
    serviceType: BridgeApi.ServiceCreateV1ResponseServiceType;
    dateOfService: string;
    externalId?: string;
    patientId: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.ServiceCreateV1ResponseLocation;
    noteId?: string;
    serviceEligibility: BridgeApi.ServiceCreateV1ResponseServiceEligibility;
    coverageStatus: BridgeApi.ServiceCreateV1ResponseCoverageStatus;
    provider: BridgeApi.ServiceCreateV1ResponseProvider;
    payments: BridgeApi.ServiceCreateV1ResponsePayment[];
    responsibleParty: BridgeApi.ServiceCreateV1ResponseResponsibleParty;
    patientResponsibility: BridgeApi.ServiceCreateV1ResponsePatientResponsibility;
    tasks: BridgeApi.ServiceCreateV1ResponseTask[];
    claimStatus?: BridgeApi.ServiceCreateV1ResponseClaimStatus;
    priorAuthorizationNumber?: string;
    cancellationReason?: BridgeApi.ServiceCreateV1ResponseCancellationReason;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.ServiceCreateV1ResponseMetadata;
}
