/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    | "ANNUAL"
    | "BENEFIT_YEAR"
    | "LIFETIME";
export const ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
