/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV1ResponseCancellationReason = "NO_SHOW";
export const ServiceCancelV1ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
