// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseServiceType {
    id: string;
    name: string;
    placeOfService: BridgeApi.ServicesListV1ResponseServiceTypeFieldPlaceOfService;
    /** [DEPRECATED] The first supported ProviderType, see new 'providerType' array */
    providerType: BridgeApi.ServicesListV1ResponseServiceTypeFieldProviderType;
    /** All supported ProviderTypes */
    providerTypes: BridgeApi.ServicesListV1ResponseServiceTypeFieldProviderType[];
    cost: number;
    noteFields: BridgeApi.ServicesListV1ResponseServiceTypeFieldNoteField[];
    conditionalPatientResponsibility: boolean;
    selfPayCost?: number;
}
