// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
export type ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType];
