/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility;
}
