// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceCreateV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType =
    (typeof ServiceCreateV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType)[keyof typeof ServiceCreateV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType];
