// This file was auto-generated by Fern from our API Definition.

export const ServiceGetV1ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type ServiceGetV1ResponsePaymentsElementType =
    (typeof ServiceGetV1ResponsePaymentsElementType)[keyof typeof ServiceGetV1ResponsePaymentsElementType];
