// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
export type ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType];
