/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceStreamV1ResponseServiceType {
    id: string;
    name: string;
    placeOfService: BridgeApi.ServiceStreamV1ResponseServiceTypeFieldPlaceOfService;
    /** [DEPRECATED] The first supported ProviderType, see new 'providerType' array */
    providerType: BridgeApi.ServiceStreamV1ResponseServiceTypeFieldProviderType;
    /** All supported ProviderTypes */
    providerTypes: BridgeApi.ServiceStreamV1ResponseServiceTypeFieldProviderType[];
    cost: number;
    noteFields: BridgeApi.ServiceStreamV1ResponseServiceTypeFieldNoteField[];
    conditionalPatientResponsibility: boolean;
    selfPayCost?: number;
}
