// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type ServicesListV1ResponsePaymentsElementType =
    (typeof ServicesListV1ResponsePaymentsElementType)[keyof typeof ServicesListV1ResponsePaymentsElementType];
