/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceUpdateV1Response {
    id: string;
    organizationId: string;
    status: BridgeApi.ServiceUpdateV1ResponseStatus;
    createdAt: string;
    serviceType: BridgeApi.ServiceUpdateV1ResponseServiceType;
    dateOfService: string;
    externalId?: string;
    patientId: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.ServiceUpdateV1ResponseLocation;
    noteId?: string;
    serviceEligibility: BridgeApi.ServiceUpdateV1ResponseServiceEligibility;
    coverageStatus: BridgeApi.ServiceUpdateV1ResponseCoverageStatus;
    provider: BridgeApi.ServiceUpdateV1ResponseProvider;
    payments: BridgeApi.ServiceUpdateV1ResponsePayment[];
    responsibleParty: BridgeApi.ServiceUpdateV1ResponseResponsibleParty;
    patientResponsibility: BridgeApi.ServiceUpdateV1ResponsePatientResponsibility;
    tasks: BridgeApi.ServiceUpdateV1ResponseTask[];
    claimStatus?: BridgeApi.ServiceUpdateV1ResponseClaimStatus;
    priorAuthorizationNumber?: string;
    cancellationReason?: BridgeApi.ServiceUpdateV1ResponseCancellationReason;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.ServiceUpdateV1ResponseMetadata;
}
