/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit {
    type: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType;
    value?: number;
    metric?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric;
    period?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod;
    units?: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits;
}
