// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV1RequestResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceUpdateV1RequestResponsibleParty =
    (typeof ServiceUpdateV1RequestResponsibleParty)[keyof typeof ServiceUpdateV1RequestResponsibleParty];
