// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export type ServicesListV1ResponseServiceTypeFieldProviderType =
    BridgeApi.ServicesListV1ResponseServiceTypeFieldProviderTypesElement;
