/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1ResponseServiceEligibility {
    id: string;
    organizationId: string;
    /** Timestamp this was executed */
    validatedAt?: string;
    serviceTypeId: string;
    dateOfService: string;
    status: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldStatus;
    patientResponsibility?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldPatientResponsibility;
    providers: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldProvider[];
    policyIds: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldPolicyId[];
    state: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldState;
    messages?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldMessage[];
    clinicalInfo?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldClinicalInfo;
    conditionalPatientResponsibilities?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibility[];
}
