/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV1ResponseLocationFieldCountry = "US";
export const ServiceCreateV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
