/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGetV1ResponseServiceTypeFieldPlaceOfService = "TELEHEALTH_HOME" | "TELEHEALTH_NOT_HOME" | "OFFICE";
export const ServiceGetV1ResponseServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
