/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseLocation {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.ServicesListV1ResponseLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.ServicesListV1ResponseLocationFieldCountry;
}
