// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit;
    /** Describes the Patient Responsibility. All dollar values are in USD cents ($15 = 1500). The 'total' is the amount that the patient owes. The breakdown are in non-oop fields. The oop fields apply when the patient has hit (or will hit) their OOP limits. */
    patientResponsibility: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility;
}
