/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV1ResponsePatientResponsibilityFieldStatus = "UNKNOWN" | "ESTIMATE" | "FINALIZED";
export const ServiceCreateV1ResponsePatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
