// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceStreamV1ResponseServiceEligibilityFieldProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.ServiceStreamV1ResponseServiceEligibilityFieldProvidersElementType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
