// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
export type ServicesListV1ResponseCancellationReason =
    (typeof ServicesListV1ResponseCancellationReason)[keyof typeof ServicesListV1ResponseCancellationReason];
