/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV1ResponsePaymentsElementType = "PATIENT" | "ADJUSTMENT";
export const ServiceCancelV1ResponsePaymentsElementType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
