// This file was auto-generated by Fern from our API Definition.

export const ServiceGetV1ResponsePatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
export type ServiceGetV1ResponsePatientResponsibilityFieldStatus =
    (typeof ServiceGetV1ResponsePatientResponsibilityFieldStatus)[keyof typeof ServiceGetV1ResponsePatientResponsibilityFieldStatus];
