/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceCancelV1ResponseLocation {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.ServiceCancelV1ResponseLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.ServiceCancelV1ResponseLocationFieldCountry;
}
