/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceNoteGetV1ResponseData {
    PATIENT_NAME?: string;
    ICD10?: BridgeApi.ServiceNoteGetV1ResponseDataFieldIcd10[];
    SUBJECTIVE?: string;
    OBJECTIVE?: string;
    ASSESSMENT?: string;
    TEXT?: string;
    PLAN?: string;
    DIAGNOSIS?: string;
    INTERVENTION?: string;
    MONITORING_AND_EVALUATION?: string;
    TELEHEALTH_DISCLAIMER?: string;
    /** Written description of time spent. Example: '10min spent preparing, 20min spent in visit, 5min spent documenting' */
    TOTAL_TIME_SPENT?: string;
    TIME_SPENT_MINUTES?: number;
    THERAPY_TIME_SPENT_MINUTES?: number;
    PRESCRIPTION_WRITTEN?: boolean;
    MEDICATION_MANAGED?: boolean;
    DATE_RANGE_START?: string;
    DATE_RANGE_END?: string;
    MONITORING_DATA?: BridgeApi.ServiceNoteGetV1ResponseDataFieldMonitoringDatum[];
}
