// This file was auto-generated by Fern from our API Definition.

export const ServiceGetV1ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
export type ServiceGetV1ResponseClaimStatus =
    (typeof ServiceGetV1ResponseClaimStatus)[keyof typeof ServiceGetV1ResponseClaimStatus];
