// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    {
        Annual: "ANNUAL",
        BenefitYear: "BENEFIT_YEAR",
        Lifetime: "LIFETIME",
    } as const;
export type ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod];
