// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseItemServiceEligibility {
    id: string;
    organizationId: string;
    /** Timestamp this was executed */
    validatedAt?: string;
    serviceTypeId: string;
    dateOfService: string;
    status: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldStatus;
    /** Describes the Patient Responsibility. All dollar values are in USD cents ($15 = 1500). The 'total' is the amount that the patient owes. The breakdown are in non-oop fields. The oop fields apply when the patient has hit (or will hit) their OOP limits. */
    patientResponsibility?: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldPatientResponsibility;
    providers: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldProvider[];
    policyIds: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldPolicyId[];
    /** 2 letter US state code */
    state: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldState;
    messages?: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldMessage[];
    clinicalInfo?: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldClinicalInfo;
    conditionalPatientResponsibilities?: BridgeApi.ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibility[];
}
