// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceStreamV1ResponseLocation {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.ServiceStreamV1ResponseLocationFieldState;
    postalCode?: string;
    country?: BridgeApi.ServiceStreamV1ResponseLocationFieldCountry;
}
