// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceGetV1ResponseProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.ServiceGetV1ResponseProviderFieldType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
