/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric =
    | "VISIT"
    | "UNITS";
export const ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
