// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1RequestResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceCreateV1RequestResponsibleParty =
    (typeof ServiceCreateV1RequestResponsibleParty)[keyof typeof ServiceCreateV1RequestResponsibleParty];
