// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponsePatientResponsibilityFieldStatus = {
    Unknown: "UNKNOWN",
    Estimate: "ESTIMATE",
    Finalized: "FINALIZED",
} as const;
export type ServiceCreateV1ResponsePatientResponsibilityFieldStatus =
    (typeof ServiceCreateV1ResponsePatientResponsibilityFieldStatus)[keyof typeof ServiceCreateV1ResponsePatientResponsibilityFieldStatus];
