// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
export type ServicesListV1ResponseLocationFieldCountry =
    (typeof ServicesListV1ResponseLocationFieldCountry)[keyof typeof ServicesListV1ResponseLocationFieldCountry];
