// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export type ServiceUpdateV1ResponseServiceTypeFieldProviderType =
    BridgeApi.ServiceUpdateV1ResponseServiceTypeFieldProviderTypesElement;
