/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility;
}
