/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseTask {
    type: BridgeApi.ServicesListV1ResponseTasksElementType;
    memo?: string;
}
