// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
export type ServiceStreamV1ResponseClaimStatus =
    (typeof ServiceStreamV1ResponseClaimStatus)[keyof typeof ServiceStreamV1ResponseClaimStatus];
