// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
export type ServiceCreateV1ResponseLocationFieldCountry =
    (typeof ServiceCreateV1ResponseLocationFieldCountry)[keyof typeof ServiceCreateV1ResponseLocationFieldCountry];
