// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
export type ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric =
    (typeof ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric)[keyof typeof ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric];
