/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceCancelV1ResponseTask {
    type: BridgeApi.ServiceCancelV1ResponseTasksElementType;
    memo?: string;
}
