/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicesListV1OrderCreatedAt = "asc" | "desc";
export const ServicesListV1OrderCreatedAt = {
    Asc: "asc",
    Desc: "desc",
} as const;
