// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV1ResponseCoverageStatus = {
    Pending: "PENDING",
    Revalidating: "REVALIDATING",
    Valid: "VALID",
    InvalidCoverage: "INVALID_COVERAGE",
    InvalidProvider: "INVALID_PROVIDER",
} as const;
export type ServiceUpdateV1ResponseCoverageStatus =
    (typeof ServiceUpdateV1ResponseCoverageStatus)[keyof typeof ServiceUpdateV1ResponseCoverageStatus];
