// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseServiceTypeFieldProviderTypesElement = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
} as const;
export type ServicesListV1ResponseServiceTypeFieldProviderTypesElement =
    (typeof ServicesListV1ResponseServiceTypeFieldProviderTypesElement)[keyof typeof ServicesListV1ResponseServiceTypeFieldProviderTypesElement];
