// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1Request {
    patientId: string;
    /** Full ISO8601 timestamp, including timezone */
    dateOfService: string;
    serviceTypeId: string;
    externalId?: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.ServiceCreateV1RequestLocation;
    providerId: string;
    serviceEligibility?: BridgeApi.ServiceCreateV1RequestServiceEligibility;
    priorAuthorizationNumber?: string;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.ServiceCreateV1RequestMetadata;
    responsibleParty?: BridgeApi.ServiceCreateV1RequestResponsibleParty;
}
