// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1ResponseServiceEligibility {
    id: string;
    organizationId: string;
    /** Timestamp this was executed */
    validatedAt?: string;
    serviceTypeId: string;
    dateOfService: string;
    status: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldStatus;
    /** Describes the Patient Responsibility. All dollar values are in USD cents ($15 = 1500). The 'total' is the amount that the patient owes. The breakdown are in non-oop fields. The oop fields apply when the patient has hit (or will hit) their OOP limits. */
    patientResponsibility?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldPatientResponsibility;
    providers: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldProvider[];
    policyIds: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldPolicyId[];
    /** 2 letter US state code */
    state: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldState;
    messages?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldMessage[];
    clinicalInfo?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldClinicalInfo;
    conditionalPatientResponsibilities?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibility[];
}
