// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    {
        Individual: "INDIVIDUAL",
        Family: "FAMILY",
    } as const;
export type ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    (typeof ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType];
