/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition {
    diagnoses?: BridgeApi.ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementConditionsElementDiagnosis[];
}
