/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponsePatientResponsibility {
    /** The most-current patient responsibility, either estimate or finalized amounts */
    amount?: BridgeApi.ServicesListV1ResponsePatientResponsibilityFieldAmount;
    /** The status of the `amount` value. `UNKNOWN` if this is not determinable, `ESTIMATE` until claims are settled, `FINALIZED` when the claims are settled. */
    status?: BridgeApi.ServicesListV1ResponsePatientResponsibilityFieldStatus;
    /** The amount (USD cents) of patient responsibility that has been paid, equal to the sum of all Payments. */
    paid?: number;
}
