// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    {
        Unknown: "UNKNOWN",
        Unlimited: "UNLIMITED",
        Limited: "LIMITED",
    } as const;
export type ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServicesListV1ResponseItemServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType];
