/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit {
    type: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType;
    value?: number;
    metric?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric;
    period?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod;
    units?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits;
}
