/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCancelV1ResponseLocationFieldCountry = "US";
export const ServiceCancelV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
