/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceUpdateV1ResponseLocationFieldCountry = "US";
export const ServiceUpdateV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
