// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceNoteGetV1Response {
    id: string;
    createdAt: string;
    serviceId: string;
    externalId?: string;
    data: BridgeApi.ServiceNoteGetV1ResponseData;
    signature: BridgeApi.ServiceNoteGetV1ResponseSignature;
    addenda: BridgeApi.ServiceNoteGetV1ResponseAddendum[];
}
