// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
export type ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType];
