// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
export type ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric =
    (typeof ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric)[keyof typeof ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric];
