// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
export type ServicesListV1ResponseItemCancellationReason =
    (typeof ServicesListV1ResponseItemCancellationReason)[keyof typeof ServicesListV1ResponseItemCancellationReason];
