/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceNoteGetV1ResponseAddendaElementSignature {
    timestamp: string;
    provider: BridgeApi.ServiceNoteGetV1ResponseAddendaElementSignatureFieldProvider;
}
