// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseClaimStatus = {
    Created: "CREATED",
    InProgress: "IN_PROGRESS",
    Paid: "PAID",
    Denied: "DENIED",
} as const;
export type ServiceCreateV1ResponseClaimStatus =
    (typeof ServiceCreateV1ResponseClaimStatus)[keyof typeof ServiceCreateV1ResponseClaimStatus];
