// This file was auto-generated by Fern from our API Definition.

export const ServiceNoteGetV1ResponseAddendaElementSignatureFieldProviderFieldType = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
} as const;
export type ServiceNoteGetV1ResponseAddendaElementSignatureFieldProviderFieldType =
    (typeof ServiceNoteGetV1ResponseAddendaElementSignatureFieldProviderFieldType)[keyof typeof ServiceNoteGetV1ResponseAddendaElementSignatureFieldProviderFieldType];
