// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceUpdateV1ResponseTask {
    type: BridgeApi.ServiceUpdateV1ResponseTasksElementType;
    memo?: string;
}
