// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseStatus = {
    Pending: "PENDING",
    Billing: "BILLING",
    Settling: "SETTLING",
    Complete: "COMPLETE",
    Triage: "TRIAGE",
    Canceled: "CANCELED",
    Denied: "DENIED",
} as const;
export type ServicesListV1ResponseStatus =
    (typeof ServicesListV1ResponseStatus)[keyof typeof ServicesListV1ResponseStatus];
