/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceUpdateV1ResponseCancellationReason = "NO_SHOW";
export const ServiceUpdateV1ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
