/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType =
    | "UNKNOWN"
    | "UNLIMITED"
    | "LIMITED";
export const ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
