// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseServiceEligibilityFieldClinicalInfo {
    diagnoses?: BridgeApi.ServicesListV1ResponseServiceEligibilityFieldClinicalInfoFieldDiagnosis[];
}
