// This file was auto-generated by Fern from our API Definition.

export const ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
export type ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServiceGetV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod];
