// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseServiceEligibilityFieldStatus = {
    Pending: "PENDING",
    Uninsured: "UNINSURED",
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
    Ineffective: "INEFFECTIVE",
} as const;
export type ServicesListV1ResponseServiceEligibilityFieldStatus =
    (typeof ServicesListV1ResponseServiceEligibilityFieldStatus)[keyof typeof ServicesListV1ResponseServiceEligibilityFieldStatus];
