/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceUpdateV1RequestResponsibleParty = "PATIENT" | "INSURANCE";
export const ServiceUpdateV1RequestResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
