// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
export type ServiceStreamV1ResponseCancellationReason =
    (typeof ServiceStreamV1ResponseCancellationReason)[keyof typeof ServiceStreamV1ResponseCancellationReason];
