// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceCreateV1ResponseServiceEligibilityFieldClinicalInfo {
    diagnoses?: BridgeApi.ServiceCreateV1ResponseServiceEligibilityFieldClinicalInfoFieldDiagnosis[];
}
