/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceUpdateV1RequestLocationFieldCountry = "US";
export const ServiceUpdateV1RequestLocationFieldCountry = {
    Us: "US",
} as const;
