// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit {
    type: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldType;
    value?: number;
    metric?: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldMetric;
    period?: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod;
    units?: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldUnits;
}
