// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceCreateV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType =
    (typeof ServiceCreateV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceCreateV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType];
