/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceUpdateV1Request {
    patientToken?: string;
    /** Full ISO8601 timestamp, including timezone */
    dateOfService?: string;
    serviceTypeId?: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location?: BridgeApi.ServiceUpdateV1RequestLocation;
    externalId?: string;
    providerId?: string;
    priorAuthorizationNumber?: string;
    responsibleParty?: BridgeApi.ServiceUpdateV1RequestResponsibleParty;
    /** Customizable object of string to string key-value data<br>Any modifications to this field will _overwrite_ the previous value */
    metadata?: BridgeApi.ServiceUpdateV1RequestMetadata;
}
