// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServiceUpdateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility;
}
