// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceCreateV1ResponseResponsibleParty =
    (typeof ServiceCreateV1ResponseResponsibleParty)[keyof typeof ServiceCreateV1ResponseResponsibleParty];
