// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServicesListV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType =
    (typeof ServicesListV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType)[keyof typeof ServicesListV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType];
