// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseItemResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServicesListV1ResponseItemResponsibleParty =
    (typeof ServicesListV1ResponseItemResponsibleParty)[keyof typeof ServicesListV1ResponseItemResponsibleParty];
