// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseResponsibleParty = {
    Patient: "PATIENT",
    Insurance: "INSURANCE",
} as const;
export type ServiceStreamV1ResponseResponsibleParty =
    (typeof ServiceStreamV1ResponseResponsibleParty)[keyof typeof ServiceStreamV1ResponseResponsibleParty];
