// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseItemProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.ServicesListV1ResponseItemProviderFieldType;
    providerEligibilityEnabled?: boolean;
    serviceEligibilityEnabled?: boolean;
    npi: string;
}
