// This file was auto-generated by Fern from our API Definition.

export type ServiceCreateV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementConditionsElementDiagnosis =
    string;
