/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceGetV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType = "INDIVIDUAL" | "FAMILY";
export const ServiceGetV1ResponsePatientResponsibilityFieldAmountFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
