/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceStreamV1Response {
    id: string;
    organizationId: string;
    status: BridgeApi.ServiceStreamV1ResponseStatus;
    createdAt: string;
    serviceType: BridgeApi.ServiceStreamV1ResponseServiceType;
    dateOfService: string;
    externalId?: string;
    patientId: string;
    /** Location of the Patient at the date of service, requires only the `state` value for telehealth */
    location: BridgeApi.ServiceStreamV1ResponseLocation;
    noteId?: string;
    serviceEligibility: BridgeApi.ServiceStreamV1ResponseServiceEligibility;
    coverageStatus: BridgeApi.ServiceStreamV1ResponseCoverageStatus;
    provider: BridgeApi.ServiceStreamV1ResponseProvider;
    payments: BridgeApi.ServiceStreamV1ResponsePayment[];
    responsibleParty: BridgeApi.ServiceStreamV1ResponseResponsibleParty;
    patientResponsibility: BridgeApi.ServiceStreamV1ResponsePatientResponsibility;
    tasks: BridgeApi.ServiceStreamV1ResponseTask[];
    claimStatus?: BridgeApi.ServiceStreamV1ResponseClaimStatus;
    priorAuthorizationNumber?: string;
    cancellationReason?: BridgeApi.ServiceStreamV1ResponseCancellationReason;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.ServiceStreamV1ResponseMetadata;
}
