// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseServiceEligibilityFieldStatus = {
    Pending: "PENDING",
    Uninsured: "UNINSURED",
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
    Ineffective: "INEFFECTIVE",
} as const;
export type ServiceStreamV1ResponseServiceEligibilityFieldStatus =
    (typeof ServiceStreamV1ResponseServiceEligibilityFieldStatus)[keyof typeof ServiceStreamV1ResponseServiceEligibilityFieldStatus];
