// This file was auto-generated by Fern from our API Definition.

export const ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
export type ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServiceStreamV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod];
