/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceStreamV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType =
    | "INDIVIDUAL"
    | "FAMILY";
export const ServiceStreamV1ResponseServiceEligibilityFieldPatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
