// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceNoteGetV1ResponseDataFieldMonitoringDatum {
    date: string;
    values: BridgeApi.ServiceNoteGetV1ResponseDataFieldMonitoringDataElementValue[];
}
