// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseServiceTypeFieldPlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
export type ServicesListV1ResponseServiceTypeFieldPlaceOfService =
    (typeof ServicesListV1ResponseServiceTypeFieldPlaceOfService)[keyof typeof ServicesListV1ResponseServiceTypeFieldPlaceOfService];
