// This file was auto-generated by Fern from our API Definition.

export const ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
export type ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimitFieldPeriod];
