/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceStreamV1ResponseCoverageStatus =
    | "PENDING"
    | "REVALIDATING"
    | "VALID"
    | "INVALID_COVERAGE"
    | "INVALID_PROVIDER";
export const ServiceStreamV1ResponseCoverageStatus = {
    Pending: "PENDING",
    Revalidating: "REVALIDATING",
    Valid: "VALID",
    InvalidCoverage: "INVALID_COVERAGE",
    InvalidProvider: "INVALID_PROVIDER",
} as const;
