// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1RequestLocationFieldCountry = {
    Us: "US",
} as const;
export type ServiceCreateV1RequestLocationFieldCountry =
    (typeof ServiceCreateV1RequestLocationFieldCountry)[keyof typeof ServiceCreateV1RequestLocationFieldCountry];
