// This file was auto-generated by Fern from our API Definition.

export const ServiceGetV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
export type ServiceGetV1ResponseLocationFieldCountry =
    (typeof ServiceGetV1ResponseLocationFieldCountry)[keyof typeof ServiceGetV1ResponseLocationFieldCountry];
