/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicesListV1ResponseLocationFieldCountry = "US";
export const ServicesListV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
