// This file was auto-generated by Fern from our API Definition.

export const ServiceUpdateV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
export type ServiceUpdateV1ResponseLocationFieldCountry =
    (typeof ServiceUpdateV1ResponseLocationFieldCountry)[keyof typeof ServiceUpdateV1ResponseLocationFieldCountry];
