// This file was auto-generated by Fern from our API Definition.

export const ServiceCreateV1ResponseServiceEligibilityFieldStatus = {
    Pending: "PENDING",
    Uninsured: "UNINSURED",
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
    Ineffective: "INEFFECTIVE",
} as const;
export type ServiceCreateV1ResponseServiceEligibilityFieldStatus =
    (typeof ServiceCreateV1ResponseServiceEligibilityFieldStatus)[keyof typeof ServiceCreateV1ResponseServiceEligibilityFieldStatus];
