/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceCreateV1ResponseCancellationReason = "NO_SHOW";
export const ServiceCreateV1ResponseCancellationReason = {
    NoShow: "NO_SHOW",
} as const;
