// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibility {
    conditions: BridgeApi.ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServicesListV1ResponseServiceEligibilityFieldConditionalPatientResponsibilitiesElementPatientResponsibility;
}
