// This file was auto-generated by Fern from our API Definition.

export const ServiceNoteGetV1ResponseAddendaElementDataFieldScoredAssessmentsElementType = {
    Phq9: "PHQ-9",
    Gad7: "GAD-7",
} as const;
export type ServiceNoteGetV1ResponseAddendaElementDataFieldScoredAssessmentsElementType =
    (typeof ServiceNoteGetV1ResponseAddendaElementDataFieldScoredAssessmentsElementType)[keyof typeof ServiceNoteGetV1ResponseAddendaElementDataFieldScoredAssessmentsElementType];
