// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface PatientConsentCreateV1Response {
    id: string;
    patientId: string;
    type: BridgeApi.patients.PatientConsentCreateV1ResponseType;
    version: string;
    consentedAt: string;
    expiresAt: string;
    status: BridgeApi.patients.PatientConsentCreateV1ResponseStatus;
}
