/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ServicesListV2Request {
    /** should be JSON-encoded, for example filter.serviceTypeId="svt_xxx" */
    "filter.serviceTypeId"?: string;
    /** should be JSON-encoded, for example filter.patientId="pat_xxx" */
    "filter.patientId"?: string;
    /** should be a JSON-encoded array, for example filter.status=["PENDING", "COMPLETE"] */
    "filter.status"?: BridgeApi.services.ServicesListV2FilterStatus[];
    /** should be JSON-encoded array, for example filter.providerId=["prv_xxx", "prv_yyy"] */
    "filter.providerId"?: BridgeApi.services.ServicesListV2FilterProviderId[];
    "order.createdAt"?: BridgeApi.services.ServicesListV2OrderCreatedAt;
    page?: number;
    limit?: number;
}
