// This file was auto-generated by Fern from our API Definition.

export const ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLicenseStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
export type ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLicenseStatus =
    (typeof ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLicenseStatus)[keyof typeof ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLicenseStatus];
