// This file was auto-generated by Fern from our API Definition.

export const ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantageFieldStatus =
    {
        Pending: "PENDING",
        Submitted: "SUBMITTED",
        Approved: "APPROVED",
        Active: "ACTIVE",
        Denied: "DENIED",
        NotApplicable: "NOT_APPLICABLE",
    } as const;
export type ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantageFieldStatus =
    (typeof ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantageFieldStatus)[keyof typeof ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantageFieldStatus];
