// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ProviderEnrollmentStatusGetV1Response {
    /** Whether initial credentialing has been completed and approved */
    credentialingApproved: boolean;
    /** Map of Payer Group slugs to enrollment status */
    payerGroups: Record<string, BridgeApi.providers.ProviderEnrollmentStatusGetV1ResponsePayerGroups>;
}
