// This file was auto-generated by Fern from our API Definition.

export const ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercialFieldStatus =
    {
        Pending: "PENDING",
        Submitted: "SUBMITTED",
        Approved: "APPROVED",
        Active: "ACTIVE",
        Denied: "DENIED",
        NotApplicable: "NOT_APPLICABLE",
    } as const;
export type ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercialFieldStatus =
    (typeof ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercialFieldStatus)[keyof typeof ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldCommercialFieldStatus];
