// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantage {
    status: BridgeApi.providers.ProviderEnrollmentStatusGetV1ResponsePayerGroupsValueStatesValueLinesOfBusinessFieldMedicareAdvantageFieldStatus;
    /** Date, string, formatted as YYYY-MM-DD */
    submittedAt?: string;
    /** Date, string, formatted as YYYY-MM-DD */
    approvedAt?: string;
    /** Date, string, formatted as YYYY-MM-DD */
    effectiveAt?: string;
    /** Date, string, formatted as YYYY-MM-DD */
    activeAt?: string;
}
