// This file was auto-generated by Fern from our API Definition.

export const PayerGroupGetV1ResponseHealthFieldStatus = {
    Healthy: "HEALTHY",
    Warning: "WARNING",
    Unhealthy: "UNHEALTHY",
} as const;
export type PayerGroupGetV1ResponseHealthFieldStatus =
    (typeof PayerGroupGetV1ResponseHealthFieldStatus)[keyof typeof PayerGroupGetV1ResponseHealthFieldStatus];
