// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface PayerGroupGetV1ResponseHealth {
    status: BridgeApi.PayerGroupGetV1ResponseHealthFieldStatus;
    lastUpdatedAt: string;
}
