// This file was auto-generated by Fern from our API Definition.

export const FeeCaptureStripeV1ResponseStatus = {
    Pending: "PENDING",
    Capturing: "CAPTURING",
    Paid: "PAID",
    Voided: "VOIDED",
    PartiallyRefunded: "PARTIALLY_REFUNDED",
    Refunded: "REFUNDED",
} as const;
export type FeeCaptureStripeV1ResponseStatus =
    (typeof FeeCaptureStripeV1ResponseStatus)[keyof typeof FeeCaptureStripeV1ResponseStatus];
