// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface FeeCaptureStripeV1Response {
    id: string;
    createdAt: string;
    patientId: string;
    serviceId?: string;
    externalId?: string;
    type: BridgeApi.billing.FeeCaptureStripeV1ResponseType;
    amount: number;
    status: BridgeApi.billing.FeeCaptureStripeV1ResponseStatus;
    stripe?: BridgeApi.billing.FeeCaptureStripeV1ResponseStripe;
}
