// This file was auto-generated by Fern from our API Definition.

export const FeeCreateV1ResponseStatus = {
    Pending: "PENDING",
    Capturing: "CAPTURING",
    Paid: "PAID",
    Voided: "VOIDED",
    PartiallyRefunded: "PARTIALLY_REFUNDED",
    Refunded: "REFUNDED",
} as const;
export type FeeCreateV1ResponseStatus = (typeof FeeCreateV1ResponseStatus)[keyof typeof FeeCreateV1ResponseStatus];
