// This file was auto-generated by Fern from our API Definition.

export const FeeRefundStripeV1ResponseStatus = {
    Pending: "PENDING",
    Capturing: "CAPTURING",
    Paid: "PAID",
    Voided: "VOIDED",
    PartiallyRefunded: "PARTIALLY_REFUNDED",
    Refunded: "REFUNDED",
} as const;
export type FeeRefundStripeV1ResponseStatus =
    (typeof FeeRefundStripeV1ResponseStatus)[keyof typeof FeeRefundStripeV1ResponseStatus];
