// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface FeeRefundStripeV1Response {
    id: string;
    createdAt: string;
    patientId: string;
    serviceId?: string;
    externalId?: string;
    type: BridgeApi.billing.FeeRefundStripeV1ResponseType;
    amount: number;
    status: BridgeApi.billing.FeeRefundStripeV1ResponseStatus;
    stripe?: BridgeApi.billing.FeeRefundStripeV1ResponseStripe;
}
