// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface FeesListV1Response {
    /** List results */
    items: BridgeApi.billing.FeesListV1ResponseItem[];
    /** Total count (if available) */
    count?: number;
}
