// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface FeesListV1ResponseItem {
    id: string;
    createdAt: string;
    updatedAt: string;
    externalId?: string;
    amount: number;
    type: BridgeApi.billing.FeesListV1ResponseItemType;
    status: BridgeApi.billing.FeesListV1ResponseItemStatus;
    patientId: string;
    serviceId?: string;
}
