// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface FeesListV1Request {
    /** should be JSON-encoded, for example filter.patientId="pat_xxx" */
    "filter.patientId"?: string;
    /** should be JSON-encoded, for example filter.serviceId="svc_xxx" */
    "filter.serviceId"?: string;
    /** should be JSON-encoded, for example filter.serviceEligibilityId="sel_xxx" */
    "filter.serviceEligibilityId"?: string;
    /** should be JSON-encoded, for example filter.status="PENDING" */
    "filter.status"?: BridgeApi.billing.FeesListV1FilterStatus;
    page?: number;
    limit?: number;
}
