// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../mock-server/MockServerPool";
import { BridgeApiClient } from "../../../src/Client";

describe("Payments", () => {
    test("listService Payments", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    createdAt: "2024-01-15T09:30:00Z",
                    serviceId: "serviceId",
                    paidAt: "2024-01-15T09:30:00Z",
                    transactionId: "transactionId",
                    type: "PATIENT",
                    amount: 1,
                    externalId: "externalId",
                    memo: "memo",
                },
                {
                    id: "id",
                    createdAt: "2024-01-15T09:30:00Z",
                    serviceId: "serviceId",
                    paidAt: "2024-01-15T09:30:00Z",
                    transactionId: "transactionId",
                    type: "PATIENT",
                    amount: 1,
                    externalId: "externalId",
                    memo: "memo",
                },
            ],
            count: 1,
        };
        server
            .mockEndpoint()
            .get("/api/services/id/payments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.services.payments.listServicePayments("id");
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    createdAt: "2024-01-15T09:30:00Z",
                    serviceId: "serviceId",
                    paidAt: "2024-01-15T09:30:00Z",
                    transactionId: "transactionId",
                    type: "PATIENT",
                    amount: 1,
                    externalId: "externalId",
                    memo: "memo",
                },
                {
                    id: "id",
                    createdAt: "2024-01-15T09:30:00Z",
                    serviceId: "serviceId",
                    paidAt: "2024-01-15T09:30:00Z",
                    transactionId: "transactionId",
                    type: "PATIENT",
                    amount: 1,
                    externalId: "externalId",
                    memo: "memo",
                },
            ],
            count: 1,
        });
    });
});
