// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteGetV1ResponseDataFieldMonitoringDatum {
    date: string;
    values: BridgeApi.NoteGetV1ResponseDataFieldMonitoringDataElementValue[];
}
