// This file was auto-generated by Fern from our API Definition.

export const NoteCreateV1ResponseAddendaElementDataFieldScoredAssessmentsElementType = {
    Phq9: "PHQ-9",
    Gad7: "GAD-7",
} as const;
export type NoteCreateV1ResponseAddendaElementDataFieldScoredAssessmentsElementType =
    (typeof NoteCreateV1ResponseAddendaElementDataFieldScoredAssessmentsElementType)[keyof typeof NoteCreateV1ResponseAddendaElementDataFieldScoredAssessmentsElementType];
