/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NoteAddendaListV1OrderCreatedAt = "asc" | "desc";
export const NoteAddendaListV1OrderCreatedAt = {
    Asc: "asc",
    Desc: "desc",
} as const;
