// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendaListV1Response {
    /** List results */
    items: BridgeApi.NoteAddendaListV1ResponseItem[];
    /** Total count (if available) */
    count?: number;
}
