// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendaListV1ResponseSignatureFieldProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.NoteAddendaListV1ResponseSignatureFieldProviderFieldType;
    providerEligibilityEnabled: boolean;
    serviceEligibilityEnabled: boolean;
    npi: string;
}
