// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendumCreateV1RequestDataFieldScoredAssessment {
    score: string;
    type: BridgeApi.NoteAddendumCreateV1RequestDataFieldScoredAssessmentsElementType;
}
