/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface NoteCreateV1Response {
    id: string;
    createdAt: string;
    serviceId: string;
    externalId?: string;
    data: BridgeApi.NoteCreateV1ResponseData;
    signature: BridgeApi.NoteCreateV1ResponseSignature;
    addenda: BridgeApi.NoteCreateV1ResponseAddendum[];
}
