// This file was auto-generated by Fern from our API Definition.

export const NoteAddendaListV1OrderCreatedAt = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type NoteAddendaListV1OrderCreatedAt =
    (typeof NoteAddendaListV1OrderCreatedAt)[keyof typeof NoteAddendaListV1OrderCreatedAt];
