// This file was auto-generated by Fern from our API Definition.

export const NoteCreateV1ResponseDataFieldScoredAssessmentsElementType = {
    Phq9: "PHQ-9",
    Gad7: "GAD-7",
} as const;
export type NoteCreateV1ResponseDataFieldScoredAssessmentsElementType =
    (typeof NoteCreateV1ResponseDataFieldScoredAssessmentsElementType)[keyof typeof NoteCreateV1ResponseDataFieldScoredAssessmentsElementType];
