// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendaListV1ResponseItemDataFieldScoredAssessment {
    score: string;
    type: BridgeApi.NoteAddendaListV1ResponseItemDataFieldScoredAssessmentsElementType;
}
