// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendaListV1ResponseItemDataFieldMonitoringDatum {
    date: string;
    values: BridgeApi.NoteAddendaListV1ResponseItemDataFieldMonitoringDataElementValue[];
}
