// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendaListV1ResponseItem {
    id: string;
    createdAt: string;
    externalId?: string;
    data: BridgeApi.NoteAddendaListV1ResponseItemData;
    signature: BridgeApi.NoteAddendaListV1ResponseItemSignature;
}
