/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface NoteCreateV1ResponseAddendaElementSignatureFieldProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.NoteCreateV1ResponseAddendaElementSignatureFieldProviderFieldType;
    providerEligibilityEnabled: boolean;
    serviceEligibilityEnabled: boolean;
    npi: string;
}
