// This file was auto-generated by Fern from our API Definition.

export const NoteCreateV1RequestDataFieldScoredAssessmentsElementType = {
    Phq9: "PHQ-9",
    Gad7: "GAD-7",
} as const;
export type NoteCreateV1RequestDataFieldScoredAssessmentsElementType =
    (typeof NoteCreateV1RequestDataFieldScoredAssessmentsElementType)[keyof typeof NoteCreateV1RequestDataFieldScoredAssessmentsElementType];
