/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface NoteAddendaListV1Response {
    id: string;
    createdAt: string;
    externalId?: string;
    data: BridgeApi.NoteAddendaListV1ResponseData;
    signature: BridgeApi.NoteAddendaListV1ResponseSignature;
}
