// This file was auto-generated by Fern from our API Definition.

export const NoteAddendumCreateV1ResponseDataFieldScoredAssessmentsElementType = {
    Phq9: "PHQ-9",
    Gad7: "GAD-7",
    SdohPrapare: "SDOH-PRAPARE",
    SdohAhcHrsn: "SDOH-AHC-HRSN",
    SdohViSpdat: "SDOH-VI-SPDAT",
    SdohCore5Sdh: "SDOH-CORE-5-SDH",
    Fast: "FAST",
    Cdr: "CDR",
    Gds: "GDS",
    Moca: "MoCA",
    Slums: "SLUMS",
    Epworth: "Epworth",
    Mmse: "MMSE",
    NpiQ: "NPI-Q",
    Bhev5Plus: "BHEV5+",
    Phq2: "PHQ-2",
} as const;
export type NoteAddendumCreateV1ResponseDataFieldScoredAssessmentsElementType =
    (typeof NoteAddendumCreateV1ResponseDataFieldScoredAssessmentsElementType)[keyof typeof NoteAddendumCreateV1ResponseDataFieldScoredAssessmentsElementType];
