// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteCreateV1ResponseAddendaElementSignature {
    timestamp: string;
    provider: BridgeApi.NoteCreateV1ResponseAddendaElementSignatureFieldProvider;
}
