// This file was auto-generated by Fern from our API Definition.

export const NoteCreateV1ResponseDataFieldScoredAssessmentsElementType = {
    Phq9: "PHQ-9",
    Gad7: "GAD-7",
    SdohPrapare: "SDOH-PRAPARE",
    SdohAhcHrsn: "SDOH-AHC-HRSN",
    SdohViSpdat: "SDOH-VI-SPDAT",
    SdohCore5Sdh: "SDOH-CORE-5-SDH",
} as const;
export type NoteCreateV1ResponseDataFieldScoredAssessmentsElementType =
    (typeof NoteCreateV1ResponseDataFieldScoredAssessmentsElementType)[keyof typeof NoteCreateV1ResponseDataFieldScoredAssessmentsElementType];
