// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteAddendumCreateV1Request {
    externalId?: string;
    data: BridgeApi.NoteAddendumCreateV1RequestData;
    signature: BridgeApi.NoteAddendumCreateV1RequestSignature;
}
