// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface NoteCreateV1RequestData {
    PATIENT_NAME?: string;
    ICD10?: BridgeApi.NoteCreateV1RequestDataFieldIcd10[];
    /** Array of medication names (e.g., ['Metformin 500mg', 'Lisinopril 10mg']) */
    MEDICATIONS?: BridgeApi.NoteCreateV1RequestDataFieldMedication[];
    /** Array of allergies (e.g., ['Penicillin', 'Peanuts']) */
    ALLERGIES?: BridgeApi.NoteCreateV1RequestDataFieldAllergy[];
    SUBJECTIVE?: string;
    OBJECTIVE?: string;
    ASSESSMENT?: string;
    TEXT?: string;
    PLAN?: string;
    DIAGNOSIS?: string;
    INTERVENTION?: string;
    MONITORING_AND_EVALUATION?: string;
    TELEHEALTH_DISCLAIMER?: string;
    /** Written description of time spent. Example: '10min spent preparing, 20min spent in visit, 5min spent documenting' */
    TOTAL_TIME_SPENT?: string;
    INDIVIDUAL_TIME_SPENT_MINUTES?: number;
    TIME_SPENT_MINUTES?: number;
    THERAPY_TIME_SPENT_MINUTES?: number;
    SMA_GROUP_SIZE?: number;
    /** Patient height in inches (in) */
    HEIGHT?: number;
    /** Patient weight in pounds (lb) */
    WEIGHT?: number;
    PRESCRIPTION_WRITTEN?: boolean;
    MEDICATION_MANAGED?: boolean;
    DATE_RANGE_START?: string;
    DATE_RANGE_END?: string;
    MONITORING_DATA?: BridgeApi.NoteCreateV1RequestDataFieldMonitoringDatum[];
    SCORED_ASSESSMENTS?: BridgeApi.NoteCreateV1RequestDataFieldScoredAssessment[];
    INITIATING_VISIT_DATE?: string;
}
