/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface NoteGetV1ResponseAddendaElementDataFieldMonitoringDatum {
    date: string;
    values: BridgeApi.NoteGetV1ResponseAddendaElementDataFieldMonitoringDataElementValue[];
}
