// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ProvidersListV1Request {
    /** Value is a raw boolean, example filter.active=true */
    "filter.active"?: boolean;
    page?: number;
    limit?: number;
}
