// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface HealthEventsListV1ResponseItem {
    id: string;
    status: BridgeApi.payerGroups.HealthEventsListV1ResponseItemStatus;
    previousStatus?: BridgeApi.payerGroups.HealthEventsListV1ResponseItemPreviousStatus;
    eventAt: string;
}
