// This file was auto-generated by Fern from our API Definition.

export const HealthEventsListV1ResponseItemPreviousStatus = {
    Healthy: "HEALTHY",
    Warning: "WARNING",
    Unhealthy: "UNHEALTHY",
} as const;
export type HealthEventsListV1ResponseItemPreviousStatus =
    (typeof HealthEventsListV1ResponseItemPreviousStatus)[keyof typeof HealthEventsListV1ResponseItemPreviousStatus];
