// This file was auto-generated by Fern from our API Definition.

export const HealthEventsListV1ResponseItemStatus = {
    Healthy: "HEALTHY",
    Warning: "WARNING",
    Unhealthy: "UNHEALTHY",
} as const;
export type HealthEventsListV1ResponseItemStatus =
    (typeof HealthEventsListV1ResponseItemStatus)[keyof typeof HealthEventsListV1ResponseItemStatus];
