// This file was auto-generated by Fern from our API Definition.

export const HealthEventsListV1OrderEventAt = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type HealthEventsListV1OrderEventAt =
    (typeof HealthEventsListV1OrderEventAt)[keyof typeof HealthEventsListV1OrderEventAt];
