// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface HealthEventsListV1Response {
    /** List results */
    items: BridgeApi.payerGroups.HealthEventsListV1ResponseItem[];
    /** Total count (if available) */
    count?: number;
}
