// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface NoteAddendaListV1Request {
    /** should be JSON-encoded, for example filter.noteId="note_xxx" */
    "filter.noteId"?: string;
    "order.createdAt"?: BridgeApi.NoteAddendaListV1OrderCreatedAt;
    page?: number;
    limit?: number;
}
