/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PatientGetV1ResponseAddress {
    line1?: string;
    line2?: string;
    city?: string;
    state: BridgeApi.PatientGetV1ResponseAddressFieldState;
    postalCode?: string;
    country?: BridgeApi.PatientGetV1ResponseAddressFieldCountry;
}
