// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface PatientsListV1ResponseItemAddress {
    line1?: string;
    line2?: string;
    city?: string;
    /** 2 letter US state code */
    state: BridgeApi.PatientsListV1ResponseItemAddressFieldState;
    postalCode?: string;
    country?: BridgeApi.PatientsListV1ResponseItemAddressFieldCountry;
}
