/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientCreateV1ResponseAddressFieldCountry = "US";
export const PatientCreateV1ResponseAddressFieldCountry = {
    Us: "US",
} as const;
