// This file was auto-generated by Fern from our API Definition.

export interface PatientUpdateV1RequestCoverage {
    /** Must be 0 (deprecated, no need to include) */
    rank?: number;
    /** Reference to an active Policy to use for this Patient */
    policyId: string;
}
