// This file was auto-generated by Fern from our API Definition.

export const PatientsListV1ResponseAccountFieldStatus = {
    Current: "CURRENT",
    Due: "DUE",
    Delinquent: "DELINQUENT",
} as const;
export type PatientsListV1ResponseAccountFieldStatus =
    (typeof PatientsListV1ResponseAccountFieldStatus)[keyof typeof PatientsListV1ResponseAccountFieldStatus];
