// This file was auto-generated by Fern from our API Definition.

export const PatientStreamV1ResponseAccountFieldStatus = {
    Current: "CURRENT",
    Due: "DUE",
    Delinquent: "DELINQUENT",
} as const;
export type PatientStreamV1ResponseAccountFieldStatus =
    (typeof PatientStreamV1ResponseAccountFieldStatus)[keyof typeof PatientStreamV1ResponseAccountFieldStatus];
