// This file was auto-generated by Fern from our API Definition.

export const PatientsListV1ResponseItemAccountFieldStatus = {
    Current: "CURRENT",
    Due: "DUE",
    Delinquent: "DELINQUENT",
} as const;
export type PatientsListV1ResponseItemAccountFieldStatus =
    (typeof PatientsListV1ResponseItemAccountFieldStatus)[keyof typeof PatientsListV1ResponseItemAccountFieldStatus];
