/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientUpdateV1ResponseAddressFieldCountry = "US";
export const PatientUpdateV1ResponseAddressFieldCountry = {
    Us: "US",
} as const;
