// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface PatientUpdateV1RequestAddress {
    line1: string;
    line2?: string;
    city: string;
    /** 2 letter US state code */
    state: BridgeApi.PatientUpdateV1RequestAddressFieldState;
    postalCode: string;
    country?: BridgeApi.PatientUpdateV1RequestAddressFieldCountry;
}
