/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientStreamV1ResponseAddressFieldCountry = "US";
export const PatientStreamV1ResponseAddressFieldCountry = {
    Us: "US",
} as const;
