/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PatientStreamV1Response {
    id: string;
    patientToken?: string;
    createdAt: string;
    externalId?: string;
    coverage: BridgeApi.PatientStreamV1ResponseCoverage[];
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    email: string;
    phone?: string;
    address?: BridgeApi.PatientStreamV1ResponseAddress;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.PatientStreamV1ResponseMetadata;
    account?: BridgeApi.PatientStreamV1ResponseAccount;
}
