// This file was auto-generated by Fern from our API Definition.

export const PatientUpdateV1ResponseAccountFieldStatus = {
    Current: "CURRENT",
    Due: "DUE",
    Delinquent: "DELINQUENT",
} as const;
export type PatientUpdateV1ResponseAccountFieldStatus =
    (typeof PatientUpdateV1ResponseAccountFieldStatus)[keyof typeof PatientUpdateV1ResponseAccountFieldStatus];
