// This file was auto-generated by Fern from our API Definition.

export const PatientUpdateV1RequestAddressFieldCountry = {
    Us: "US",
} as const;
export type PatientUpdateV1RequestAddressFieldCountry =
    (typeof PatientUpdateV1RequestAddressFieldCountry)[keyof typeof PatientUpdateV1RequestAddressFieldCountry];
