/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PatientsListV1ResponseAccount {
    status: BridgeApi.PatientsListV1ResponseAccountFieldStatus;
    balance: number;
}
