// This file was auto-generated by Fern from our API Definition.

export const PatientUpdateV1ResponseAddressFieldCountry = {
    Us: "US",
} as const;
export type PatientUpdateV1ResponseAddressFieldCountry =
    (typeof PatientUpdateV1ResponseAddressFieldCountry)[keyof typeof PatientUpdateV1ResponseAddressFieldCountry];
