/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PatientGetV1Response {
    id: string;
    patientToken?: string;
    createdAt: string;
    externalId?: string;
    coverage: BridgeApi.PatientGetV1ResponseCoverage[];
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    email: string;
    phone?: string;
    address?: BridgeApi.PatientGetV1ResponseAddress;
    /** Customizable object of string to string key-value data */
    metadata?: BridgeApi.PatientGetV1ResponseMetadata;
    account?: BridgeApi.PatientGetV1ResponseAccount;
    stripeId?: string;
}
