// This file was auto-generated by Fern from our API Definition.

export const PatientStreamV1ResponseAddressFieldCountry = {
    Us: "US",
} as const;
export type PatientStreamV1ResponseAddressFieldCountry =
    (typeof PatientStreamV1ResponseAddressFieldCountry)[keyof typeof PatientStreamV1ResponseAddressFieldCountry];
