/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientGetV1ResponseAddressFieldCountry = "US";
export const PatientGetV1ResponseAddressFieldCountry = {
    Us: "US",
} as const;
