// This file was auto-generated by Fern from our API Definition.

export const PolicyCreateV2ResponseStatus = {
    Pending: "PENDING",
    Unknown: "UNKNOWN",
    Confirmed: "CONFIRMED",
    Revalidating: "REVALIDATING",
    Invalid: "INVALID",
} as const;
export type PolicyCreateV2ResponseStatus =
    (typeof PolicyCreateV2ResponseStatus)[keyof typeof PolicyCreateV2ResponseStatus];
