/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PolicyCreateV2ResponsePerson {
    firstName: string;
    middleName?: string;
    lastName: string;
    dateOfBirth?: string;
}
