// This file was auto-generated by Fern from our API Definition.

export const PolicyCreateV2ResponseRelationship = {
    Self: "SELF",
    Child: "CHILD",
    Spouse: "SPOUSE",
    Other: "OTHER",
    None: "NONE",
} as const;
export type PolicyCreateV2ResponseRelationship =
    (typeof PolicyCreateV2ResponseRelationship)[keyof typeof PolicyCreateV2ResponseRelationship];
