/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PolicyCreateV2ResponseRelationship = "SELF" | "CHILD" | "SPOUSE" | "OTHER" | "NONE";
export const PolicyCreateV2ResponseRelationship = {
    Self: "SELF",
    Child: "CHILD",
    Spouse: "SPOUSE",
    Other: "OTHER",
    None: "NONE",
} as const;
