// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface PaymentsListV1Request {
    /** Values should be JSON-encoded, for example filter.patientId="pat_xxx" */
    "filter.patientId"?: string;
    /** Values should be JSON-encoded, for example filter.serviceId="svc_xxx" */
    "filter.serviceId"?: string;
    /** Values should be JSON-encoded, for example filter.type="PATIENT" */
    "filter.type"?: BridgeApi.PaymentsListV1FilterType;
    "order.paidAt"?: BridgeApi.PaymentsListV1OrderPaidAt;
    page?: number;
    limit?: number;
}
