/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ProviderEligibilityGetV1Response {
    id: string;
    /** Timestamp this was executed */
    validatedAt: string;
    dateOfService: string;
    serviceTypeId: string;
    location: BridgeApi.ProviderEligibilityGetV1ResponseLocation;
    payerId: string;
    /** The eligibility status of this check. Note, the patient may be eligible on a location/payer-basis, but providers are not available. Use a combination of this _and_ the `providers` array to determine next steps. */
    status: BridgeApi.ProviderEligibilityGetV1ResponseStatus;
    providers: BridgeApi.ProviderEligibilityGetV1ResponseProvider[];
}
