/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProviderEligibilityCreateV1ResponseStatus = "ELIGIBLE" | "INELIGIBLE";
export const ProviderEligibilityCreateV1ResponseStatus = {
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
} as const;
