// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ProviderEligibilityCreateV1ResponseProvider {
    id: string;
    name: string;
    externalId?: string;
    type: BridgeApi.ProviderEligibilityCreateV1ResponseProvidersElementType;
    providerEligibilityEnabled: boolean;
    serviceEligibilityEnabled: boolean;
    npi: string;
}
