/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProviderEligibilityCreateV1RequestLocationFieldCountry = "US";
export const ProviderEligibilityCreateV1RequestLocationFieldCountry = {
    Us: "US",
} as const;
