/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProviderEligibilityGetV1ResponseLocationFieldCountry = "US";
export const ProviderEligibilityGetV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
