// This file was auto-generated by Fern from our API Definition.

export const ProviderEligibilityGetV1ResponseStatus = {
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
} as const;
export type ProviderEligibilityGetV1ResponseStatus =
    (typeof ProviderEligibilityGetV1ResponseStatus)[keyof typeof ProviderEligibilityGetV1ResponseStatus];
