/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProviderEligibilityCreateV1ResponseLocationFieldCountry = "US";
export const ProviderEligibilityCreateV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
