// This file was auto-generated by Fern from our API Definition.

export const ProviderEligibilityGetV1ResponseProvidersElementType = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
} as const;
export type ProviderEligibilityGetV1ResponseProvidersElementType =
    (typeof ProviderEligibilityGetV1ResponseProvidersElementType)[keyof typeof ProviderEligibilityGetV1ResponseProvidersElementType];
