// This file was auto-generated by Fern from our API Definition.

export const ProviderEligibilityGetV1ResponseLocationFieldCountry = {
    Us: "US",
} as const;
export type ProviderEligibilityGetV1ResponseLocationFieldCountry =
    (typeof ProviderEligibilityGetV1ResponseLocationFieldCountry)[keyof typeof ProviderEligibilityGetV1ResponseLocationFieldCountry];
