/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    "INDIVIDUAL" | "FAMILY";
export const ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    {
        Individual: "INDIVIDUAL",
        Family: "FAMILY",
    } as const;
