/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityCreateV1Request {
    serviceTypeId: string;
    /** Full ISO8601 timestamp, including timezone */
    dateOfService: string;
    policyIds: BridgeApi.ServiceEligibilityCreateV1RequestPolicyId[];
    state: BridgeApi.ServiceEligibilityCreateV1RequestState;
    clinicalInfo?: BridgeApi.ServiceEligibilityCreateV1RequestClinicalInfo;
}
