// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    {
        Individual: "INDIVIDUAL",
        Family: "FAMILY",
    } as const;
export type ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType =
    (typeof ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType)[keyof typeof ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibilityFieldDeductibleType];
