// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
export type ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric =
    (typeof ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric)[keyof typeof ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric];
