// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
export type ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod];
