/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityCreateV1ResponseClinicalInfo {
    diagnoses?: BridgeApi.ServiceEligibilityCreateV1ResponseClinicalInfoFieldDiagnosis[];
}
