// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod = {
    Annual: "ANNUAL",
    BenefitYear: "BENEFIT_YEAR",
    Lifetime: "LIFETIME",
} as const;
export type ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod =
    (typeof ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod)[keyof typeof ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod];
