// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityStreamV1ResponseStatus = {
    Pending: "PENDING",
    Uninsured: "UNINSURED",
    Eligible: "ELIGIBLE",
    Ineligible: "INELIGIBLE",
    Ineffective: "INEFFECTIVE",
} as const;
export type ServiceEligibilityStreamV1ResponseStatus =
    (typeof ServiceEligibilityStreamV1ResponseStatus)[keyof typeof ServiceEligibilityStreamV1ResponseStatus];
