/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityStreamV1ResponseConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibility;
}
