// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType =
    (typeof ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType)[keyof typeof ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType];
