/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimit {
    type: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType;
    value?: number;
    metric?: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric;
    period?: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldPeriod;
    units?: BridgeApi.ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldUnits;
}
