/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType = "INDIVIDUAL" | "FAMILY";
export const ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
