/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityCreateV1ResponseConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceEligibilityCreateV1ResponseConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceEligibilityCreateV1ResponseConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServiceEligibilityCreateV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibility;
}
