// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityGetV1ResponsePatientResponsibility {
    total: number;
    fallback: number;
    deductible: number;
    deductibleType?: BridgeApi.ServiceEligibilityGetV1ResponsePatientResponsibilityFieldDeductibleType;
    coinsurance: number;
    coinsurancePercent: number;
    copayment: number;
    oopFallback: number;
    oopCopayment: number;
    oopCoinsurance: number;
    oopDeductible: number;
}
