// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
export type ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric =
    (typeof ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric)[keyof typeof ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric];
