// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
export type ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType =
    (typeof ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType)[keyof typeof ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType];
