// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface ServiceEligibilityGetV1ResponseConditionalPatientResponsibility {
    conditions: BridgeApi.ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementCondition[];
    limit: BridgeApi.ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementLimit;
    patientResponsibility: BridgeApi.ServiceEligibilityGetV1ResponseConditionalPatientResponsibilitiesElementPatientResponsibility;
}
