/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityCreateV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric =
    | "VISIT"
    | "UNITS";
export const ServiceEligibilityCreateV1ResponseConditionalPatientResponsibilitiesElementLimitFieldMetric = {
    Visit: "VISIT",
    Units: "UNITS",
} as const;
