/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType =
    | "UNKNOWN"
    | "UNLIMITED"
    | "LIMITED";
export const ServiceEligibilityStreamV1ResponseConditionalPatientResponsibilitiesElementLimitFieldType = {
    Unknown: "UNKNOWN",
    Unlimited: "UNLIMITED",
    Limited: "LIMITED",
} as const;
