// This file was auto-generated by Fern from our API Definition.

export const ServiceEligibilityStreamV1ResponsePatientResponsibilityFieldDeductibleType = {
    Individual: "INDIVIDUAL",
    Family: "FAMILY",
} as const;
export type ServiceEligibilityStreamV1ResponsePatientResponsibilityFieldDeductibleType =
    (typeof ServiceEligibilityStreamV1ResponsePatientResponsibilityFieldDeductibleType)[keyof typeof ServiceEligibilityStreamV1ResponsePatientResponsibilityFieldDeductibleType];
