// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../mock-server/MockServerPool";
import { BridgeApiClient } from "../../../src/Client";

describe("EstimateCharges", () => {
    test("createEstimate Charge", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { patientId: "patientId", serviceEligibilityId: "serviceEligibilityId" };
        const rawResponseBody = {
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
        };
        server
            .mockEndpoint()
            .post("/api/estimate-charges")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.estimateCharges.createEstimateCharge({
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
        });
        expect(response).toEqual({
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
        });
    });

    test("authorizeStripeEstimate Charge", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: { key: "value" },
                next_action: { key: "value" },
            },
        };
        server
            .mockEndpoint()
            .post("/api/estimate-charges/id/authorize/stripe")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.estimateCharges.authorizeStripeEstimateCharge("id");
        expect(response).toEqual({
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: {
                    key: "value",
                },
                next_action: {
                    key: "value",
                },
            },
        });
    });

    test("captureStripeEstimate Charge", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: { key: "value" },
                next_action: { key: "value" },
            },
        };
        server
            .mockEndpoint()
            .post("/api/estimate-charges/id/capture/stripe")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.estimateCharges.captureStripeEstimateCharge("id");
        expect(response).toEqual({
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: {
                    key: "value",
                },
                next_action: {
                    key: "value",
                },
            },
        });
    });

    test("refundStripeEstimate Charge", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: { key: "value" },
                next_action: { key: "value" },
            },
        };
        server
            .mockEndpoint()
            .post("/api/estimate-charges/id/refund/stripe")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.estimateCharges.refundStripeEstimateCharge("id");
        expect(response).toEqual({
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: {
                    key: "value",
                },
                next_action: {
                    key: "value",
                },
            },
        });
    });

    test("cancelStripeEstimate Charge", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: { key: "value" },
                next_action: { key: "value" },
            },
        };
        server
            .mockEndpoint()
            .post("/api/estimate-charges/id/cancel/stripe")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.estimateCharges.cancelStripeEstimateCharge("id");
        expect(response).toEqual({
            id: "id",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            patientId: "patientId",
            serviceEligibilityId: "serviceEligibilityId",
            externalId: "externalId",
            amount: 1,
            status: "PENDING",
            stripe: {
                status: "status",
                client_secret: "client_secret",
                last_payment_error: {
                    key: "value",
                },
                next_action: {
                    key: "value",
                },
            },
        });
    });
});
