/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { BridgeApiClient } from "../../../src/Client";

describe("V2", () => {
    test("createPatient", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", xRequestId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            externalId: undefined,
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            dateOfBirth: "2024-01-15T09:30:00Z",
            phone: undefined,
            address: undefined,
            coverage: undefined,
            metadata: undefined,
        };
        const rawResponseBody = {
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                { id: "id", rank: 1, policyId: "policyId" },
                { id: "id", rank: 1, policyId: "policyId" },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: { exampleKey: "exampleKey" },
            account: { status: "CURRENT", balance: 1 },
            stripeId: "stripeId",
        };
        server
            .mockEndpoint()
            .post("/api/patients/v2")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.patients.v2.createPatient({
            externalId: undefined,
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            dateOfBirth: "2024-01-15T09:30:00Z",
            phone: undefined,
            address: undefined,
            coverage: undefined,
            metadata: undefined,
        });
        expect(response).toEqual({
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: {
                exampleKey: "exampleKey",
            },
            account: {
                status: "CURRENT",
                balance: 1,
            },
            stripeId: "stripeId",
        });
    });

    test("getPatient", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", xRequestId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                { id: "id", rank: 1, policyId: "policyId" },
                { id: "id", rank: 1, policyId: "policyId" },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: { exampleKey: "exampleKey" },
            account: { status: "CURRENT", balance: 1 },
            stripeId: "stripeId",
        };
        server
            .mockEndpoint()
            .get("/api/patients/v2/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.patients.v2.getPatient("id");
        expect(response).toEqual({
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: {
                exampleKey: "exampleKey",
            },
            account: {
                status: "CURRENT",
                balance: 1,
            },
            stripeId: "stripeId",
        });
    });

    test("updatePatient", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", xRequestId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            patientToken: undefined,
            externalId: undefined,
            coverage: undefined,
            firstName: undefined,
            lastName: undefined,
            email: undefined,
            dateOfBirth: undefined,
            phone: undefined,
            address: undefined,
            metadata: undefined,
        };
        const rawResponseBody = {
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                { id: "id", rank: 1, policyId: "policyId" },
                { id: "id", rank: 1, policyId: "policyId" },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: { exampleKey: "exampleKey" },
            account: { status: "CURRENT", balance: 1 },
            stripeId: "stripeId",
        };
        server
            .mockEndpoint()
            .post("/api/patients/v2/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.patients.v2.updatePatient("id", {
            patientToken: undefined,
            externalId: undefined,
            coverage: undefined,
            firstName: undefined,
            lastName: undefined,
            email: undefined,
            dateOfBirth: undefined,
            phone: undefined,
            address: undefined,
            metadata: undefined,
        });
        expect(response).toEqual({
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: {
                exampleKey: "exampleKey",
            },
            account: {
                status: "CURRENT",
                balance: 1,
            },
            stripeId: "stripeId",
        });
    });
});
