/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceTypesListV1ResponseProviderTypesElement =
    | "MD"
    | "NP"
    | "DO"
    | "ND"
    | "AP"
    | "OT"
    | "LCSW"
    | "RN"
    | "CN"
    | "CWC"
    | "CM"
    | "PA"
    | "RDN";
export const ServiceTypesListV1ResponseProviderTypesElement = {
    Md: "MD",
    Np: "NP",
    Do: "DO",
    Nd: "ND",
    Ap: "AP",
    Ot: "OT",
    Lcsw: "LCSW",
    Rn: "RN",
    Cn: "CN",
    Cwc: "CWC",
    Cm: "CM",
    Pa: "PA",
    Rdn: "RDN",
} as const;
