// This file was auto-generated by Fern from our API Definition.

export const ServiceTypeGetV1ResponsePlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
export type ServiceTypeGetV1ResponsePlaceOfService =
    (typeof ServiceTypeGetV1ResponsePlaceOfService)[keyof typeof ServiceTypeGetV1ResponsePlaceOfService];
