/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceTypeGetV1ResponsePlaceOfService = "TELEHEALTH_HOME" | "TELEHEALTH_NOT_HOME" | "OFFICE";
export const ServiceTypeGetV1ResponsePlaceOfService = {
    TelehealthHome: "TELEHEALTH_HOME",
    TelehealthNotHome: "TELEHEALTH_NOT_HOME",
    Office: "OFFICE",
} as const;
