/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("ConsentVersions", () => {
    test("listConsentVersions", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "ASSIGNMENT_OF_BENEFITS", version: "version" };
        server
            .mockEndpoint()
            .get("/api/consent-versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.consentVersions.listConsentVersions();
        expect(response).toEqual({
            type: "ASSIGNMENT_OF_BENEFITS",
            version: "version",
        });
    });
});
