// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("ConsentVersions", () => {
    test("listConsentVersions", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                { type: "ASSIGNMENT_OF_BENEFITS", version: "version" },
                { type: "ASSIGNMENT_OF_BENEFITS", version: "version" },
            ],
            count: 1,
        };
        server
            .mockEndpoint()
            .get("/api/consent-versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.consentVersions.listConsentVersions();
        expect(response).toEqual({
            items: [
                {
                    type: "ASSIGNMENT_OF_BENEFITS",
                    version: "version",
                },
                {
                    type: "ASSIGNMENT_OF_BENEFITS",
                    version: "version",
                },
            ],
            count: 1,
        });
    });
});
