// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("Events", () => {
    test("listEvents", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            apiVersion: "apiVersion",
            eventId: "eventId",
            createdAt: "2024-01-15T09:30:00Z",
            eventType: "patient.created",
            objectType: "objectType",
            objectId: "objectId",
            data: { key: "value" },
            previous: { key: "value" },
        };
        server.mockEndpoint().get("/api/events").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.events.listEvents();
        expect(response).toEqual({
            apiVersion: "apiVersion",
            eventId: "eventId",
            createdAt: "2024-01-15T09:30:00Z",
            eventType: "patient.created",
            objectType: "objectType",
            objectId: "objectId",
            data: {
                key: "value",
            },
            previous: {
                key: "value",
            },
        });
    });

    test("getEvent", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            apiVersion: "apiVersion",
            eventId: "eventId",
            createdAt: "2024-01-15T09:30:00Z",
            eventType: "patient.created",
            objectType: "objectType",
            objectId: "objectId",
            data: { key: "value" },
            previous: { key: "value" },
        };
        server.mockEndpoint().get("/api/events/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.events.getEvent("id");
        expect(response).toEqual({
            apiVersion: "apiVersion",
            eventId: "eventId",
            createdAt: "2024-01-15T09:30:00Z",
            eventType: "patient.created",
            objectType: "objectType",
            objectId: "objectId",
            data: {
                key: "value",
            },
            previous: {
                key: "value",
            },
        });
    });
});
