// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";
import * as BridgeApi from "../../src/api/index";

describe("Patients", () => {
    test("listPatients", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    patientToken: "patientToken",
                    createdAt: "2024-01-15T09:30:00Z",
                    externalId: "externalId",
                    coverage: [
                        { id: "id", rank: 1, policyId: "policyId" },
                        { id: "id", rank: 1, policyId: "policyId" },
                    ],
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2024-01-15T09:30:00Z",
                    email: "email",
                    phone: "phone",
                    address: {
                        line1: "line1",
                        line2: "line2",
                        city: "city",
                        state: "AL",
                        postalCode: "postalCode",
                        country: "US",
                    },
                    metadata: { exampleKey: "exampleKey" },
                    account: { status: "CURRENT", balance: 1 },
                },
                {
                    id: "id",
                    patientToken: "patientToken",
                    createdAt: "2024-01-15T09:30:00Z",
                    externalId: "externalId",
                    coverage: [
                        { id: "id", rank: 1, policyId: "policyId" },
                        { id: "id", rank: 1, policyId: "policyId" },
                    ],
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2024-01-15T09:30:00Z",
                    email: "email",
                    phone: "phone",
                    address: {
                        line1: "line1",
                        line2: "line2",
                        city: "city",
                        state: "AL",
                        postalCode: "postalCode",
                        country: "US",
                    },
                    metadata: { exampleKey: "exampleKey" },
                    account: { status: "CURRENT", balance: 1 },
                },
            ],
            count: 1,
        };
        server.mockEndpoint().get("/api/patients").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.patients.listPatients();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    patientToken: "patientToken",
                    createdAt: "2024-01-15T09:30:00Z",
                    externalId: "externalId",
                    coverage: [
                        {
                            id: "id",
                            rank: 1,
                            policyId: "policyId",
                        },
                        {
                            id: "id",
                            rank: 1,
                            policyId: "policyId",
                        },
                    ],
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2024-01-15T09:30:00Z",
                    email: "email",
                    phone: "phone",
                    address: {
                        line1: "line1",
                        line2: "line2",
                        city: "city",
                        state: "AL",
                        postalCode: "postalCode",
                        country: "US",
                    },
                    metadata: {
                        exampleKey: "exampleKey",
                    },
                    account: {
                        status: "CURRENT",
                        balance: 1,
                    },
                },
                {
                    id: "id",
                    patientToken: "patientToken",
                    createdAt: "2024-01-15T09:30:00Z",
                    externalId: "externalId",
                    coverage: [
                        {
                            id: "id",
                            rank: 1,
                            policyId: "policyId",
                        },
                        {
                            id: "id",
                            rank: 1,
                            policyId: "policyId",
                        },
                    ],
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2024-01-15T09:30:00Z",
                    email: "email",
                    phone: "phone",
                    address: {
                        line1: "line1",
                        line2: "line2",
                        city: "city",
                        state: "AL",
                        postalCode: "postalCode",
                        country: "US",
                    },
                    metadata: {
                        exampleKey: "exampleKey",
                    },
                    account: {
                        status: "CURRENT",
                        balance: 1,
                    },
                },
            ],
            count: 1,
        });
    });

    test("updatePatient", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                { id: "id", rank: 1, policyId: "policyId" },
                { id: "id", rank: 1, policyId: "policyId" },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: { exampleKey: "exampleKey" },
            account: { status: "CURRENT", balance: 1 },
        };
        server
            .mockEndpoint()
            .post("/api/patients/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.patients.updatePatient("id", {});
        expect(response).toEqual({
            id: "id",
            patientToken: "patientToken",
            createdAt: "2024-01-15T09:30:00Z",
            externalId: "externalId",
            coverage: [
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
                {
                    id: "id",
                    rank: 1,
                    policyId: "policyId",
                },
            ],
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2024-01-15T09:30:00Z",
            email: "email",
            phone: "phone",
            address: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            metadata: {
                exampleKey: "exampleKey",
            },
            account: {
                status: "CURRENT",
                balance: 1,
            },
        });
    });

    test("revalidatePatient", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/api/patients/id/revalidate").respondWith().statusCode(200).build();

        const response = await client.patients.revalidatePatient("id");
        expect(response).toEqual(undefined);
    });
});
