/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("Payers", () => {
    test("getPayer", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { id: "id", code: "code", name: "name", memberId: true, hint: "hint" };
        server.mockEndpoint().get("/api/payers/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.payers.getPayer("id");
        expect(response).toEqual({
            id: "id",
            code: "code",
            name: "name",
            memberId: true,
            hint: "hint",
        });
    });
});
