// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";
import * as BridgeApi from "../../src/api/index";

describe("Providers", () => {
    test("postSubmit Provider", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            providers: [
                {
                    npi: "npi",
                    email: "email",
                    caqhId: "caqhId",
                    caqhUsername: "caqhUsername",
                    caqhPassword: "caqhPassword",
                },
                {
                    npi: "npi",
                    email: "email",
                    caqhId: "caqhId",
                    caqhUsername: "caqhUsername",
                    caqhPassword: "caqhPassword",
                },
            ],
        };
        const rawResponseBody = {
            failed: [
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    error: "error",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerType: "MD",
                },
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    error: "error",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerType: "MD",
                },
            ],
            submit: [
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerId: "providerId",
                    providerType: "MD",
                },
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerId: "providerId",
                    providerType: "MD",
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/api/providers/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.providers.postSubmitProvider({
            providers: [
                {
                    npi: "npi",
                    email: "email",
                    caqhId: "caqhId",
                    caqhUsername: "caqhUsername",
                    caqhPassword: "caqhPassword",
                },
                {
                    npi: "npi",
                    email: "email",
                    caqhId: "caqhId",
                    caqhUsername: "caqhUsername",
                    caqhPassword: "caqhPassword",
                },
            ],
        });
        expect(response).toEqual({
            failed: [
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    error: "error",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerType: "MD",
                },
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    error: "error",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerType: "MD",
                },
            ],
            submit: [
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerId: "providerId",
                    providerType: "MD",
                },
                {
                    caqhId: "caqhId",
                    credential: "credential",
                    email: "email",
                    externalId: "externalId",
                    firstName: "firstName",
                    lastName: "lastName",
                    npi: "npi",
                    providerId: "providerId",
                    providerType: "MD",
                },
            ],
        });
    });

    test("listProviders", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
            count: 1,
        };
        server.mockEndpoint().get("/api/providers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.providers.listProviders();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
            count: 1,
        });
    });

    test("getProvider", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            externalId: "externalId",
            type: "MD",
            providerEligibilityEnabled: true,
            serviceEligibilityEnabled: true,
            npi: "npi",
        };
        server.mockEndpoint().get("/api/providers/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.providers.getProvider("id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            externalId: "externalId",
            type: "MD",
            providerEligibilityEnabled: true,
            serviceEligibilityEnabled: true,
            npi: "npi",
        });
    });

    test("updateProvider", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            externalId: "externalId",
            type: "MD",
            providerEligibilityEnabled: true,
            serviceEligibilityEnabled: true,
            npi: "npi",
        };
        server
            .mockEndpoint()
            .post("/api/providers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.providers.updateProvider("id", {});
        expect(response).toEqual({
            id: "id",
            name: "name",
            externalId: "externalId",
            type: "MD",
            providerEligibilityEnabled: true,
            serviceEligibilityEnabled: true,
            npi: "npi",
        });
    });
});
