// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("ProviderEligibility", () => {
    test("createProviderEligibility", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            dateOfService: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            location: { state: "AL" },
            payerId: "payerId",
        };
        const rawResponseBody = {
            id: "id",
            validatedAt: "2024-01-15T09:30:00Z",
            dateOfService: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            location: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            payerId: "payerId",
            status: "ELIGIBLE",
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/api/provider-eligibility")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.providerEligibility.createProviderEligibility({
            dateOfService: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            location: {
                state: "AL",
            },
            payerId: "payerId",
        });
        expect(response).toEqual({
            id: "id",
            validatedAt: "2024-01-15T09:30:00Z",
            dateOfService: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            location: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            payerId: "payerId",
            status: "ELIGIBLE",
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
        });
    });

    test("getProviderEligibility", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            validatedAt: "2024-01-15T09:30:00Z",
            dateOfService: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            location: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            payerId: "payerId",
            status: "ELIGIBLE",
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/api/provider-eligibility/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.providerEligibility.getProviderEligibility("id");
        expect(response).toEqual({
            id: "id",
            validatedAt: "2024-01-15T09:30:00Z",
            dateOfService: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            location: {
                line1: "line1",
                line2: "line2",
                city: "city",
                state: "AL",
                postalCode: "postalCode",
                country: "US",
            },
            payerId: "payerId",
            status: "ELIGIBLE",
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
        });
    });
});
