/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("Search", () => {
    test("payerSearch", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query", limit: 1 };
        const rawResponseBody = {
            items: [
                { id: "id", code: "code", name: "name", memberId: true, hint: "hint" },
                { id: "id", code: "code", name: "name", memberId: true, hint: "hint" },
            ],
            _time: 1,
        };
        server
            .mockEndpoint()
            .post("/api/search/payers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search.payerSearch({
            query: "query",
            limit: 1,
        });
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    code: "code",
                    name: "name",
                    memberId: true,
                    hint: "hint",
                },
                {
                    id: "id",
                    code: "code",
                    name: "name",
                    memberId: true,
                    hint: "hint",
                },
            ],
            _time: 1,
        });
    });
});
