/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BridgeApiClient } from "../../src/Client";

describe("ServiceEligibility", () => {
    test("createServiceEligibility", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", xRequestId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            serviceTypeId: "serviceTypeId",
            dateOfService: "2024-01-15T09:30:00Z",
            policyIds: ["policyIds", "policyIds"],
            state: "AL",
            clinicalInfo: undefined,
        };
        const rawResponseBody = {
            id: "id",
            organizationId: "organizationId",
            validatedAt: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            dateOfService: "2024-01-15T09:30:00Z",
            status: "PENDING",
            patientResponsibility: {
                total: 1,
                fallback: 1,
                deductible: 1,
                deductibleType: "INDIVIDUAL",
                coinsurance: 1,
                coinsurancePercent: 1,
                copayment: 1,
                oopFallback: 1,
                oopCopayment: 1,
                oopCoinsurance: 1,
                oopDeductible: 1,
            },
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
            policyIds: ["policyIds", "policyIds"],
            state: "AL",
            messages: ["messages", "messages"],
            clinicalInfo: { diagnoses: ["diagnoses", "diagnoses"] },
            conditionalPatientResponsibilities: [
                {
                    conditions: [{ diagnoses: ["diagnoses", "diagnoses"] }, { diagnoses: ["diagnoses", "diagnoses"] }],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: { minutes: 1, min: 1, max: 1 },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
                {
                    conditions: [{ diagnoses: ["diagnoses", "diagnoses"] }, { diagnoses: ["diagnoses", "diagnoses"] }],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: { minutes: 1, min: 1, max: 1 },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/api/service-eligibility")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.serviceEligibility.createServiceEligibility({
            serviceTypeId: "serviceTypeId",
            dateOfService: "2024-01-15T09:30:00Z",
            policyIds: ["policyIds", "policyIds"],
            state: "AL",
            clinicalInfo: undefined,
        });
        expect(response).toEqual({
            id: "id",
            organizationId: "organizationId",
            validatedAt: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            dateOfService: "2024-01-15T09:30:00Z",
            status: "PENDING",
            patientResponsibility: {
                total: 1,
                fallback: 1,
                deductible: 1,
                deductibleType: "INDIVIDUAL",
                coinsurance: 1,
                coinsurancePercent: 1,
                copayment: 1,
                oopFallback: 1,
                oopCopayment: 1,
                oopCoinsurance: 1,
                oopDeductible: 1,
            },
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
            policyIds: ["policyIds", "policyIds"],
            state: "AL",
            messages: ["messages", "messages"],
            clinicalInfo: {
                diagnoses: ["diagnoses", "diagnoses"],
            },
            conditionalPatientResponsibilities: [
                {
                    conditions: [
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                    ],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: {
                            minutes: 1,
                            min: 1,
                            max: 1,
                        },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
                {
                    conditions: [
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                    ],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: {
                            minutes: 1,
                            min: 1,
                            max: 1,
                        },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
            ],
        });
    });

    test("getServiceEligibility", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", xRequestId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            organizationId: "organizationId",
            validatedAt: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            dateOfService: "2024-01-15T09:30:00Z",
            status: "PENDING",
            patientResponsibility: {
                total: 1,
                fallback: 1,
                deductible: 1,
                deductibleType: "INDIVIDUAL",
                coinsurance: 1,
                coinsurancePercent: 1,
                copayment: 1,
                oopFallback: 1,
                oopCopayment: 1,
                oopCoinsurance: 1,
                oopDeductible: 1,
            },
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
            policyIds: ["policyIds", "policyIds"],
            state: "AL",
            messages: ["messages", "messages"],
            clinicalInfo: { diagnoses: ["diagnoses", "diagnoses"] },
            conditionalPatientResponsibilities: [
                {
                    conditions: [{ diagnoses: ["diagnoses", "diagnoses"] }, { diagnoses: ["diagnoses", "diagnoses"] }],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: { minutes: 1, min: 1, max: 1 },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
                {
                    conditions: [{ diagnoses: ["diagnoses", "diagnoses"] }, { diagnoses: ["diagnoses", "diagnoses"] }],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: { minutes: 1, min: 1, max: 1 },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/api/service-eligibility/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.serviceEligibility.getServiceEligibility("id");
        expect(response).toEqual({
            id: "id",
            organizationId: "organizationId",
            validatedAt: "2024-01-15T09:30:00Z",
            serviceTypeId: "serviceTypeId",
            dateOfService: "2024-01-15T09:30:00Z",
            status: "PENDING",
            patientResponsibility: {
                total: 1,
                fallback: 1,
                deductible: 1,
                deductibleType: "INDIVIDUAL",
                coinsurance: 1,
                coinsurancePercent: 1,
                copayment: 1,
                oopFallback: 1,
                oopCopayment: 1,
                oopCoinsurance: 1,
                oopDeductible: 1,
            },
            providers: [
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
                {
                    id: "id",
                    name: "name",
                    externalId: "externalId",
                    type: "MD",
                    providerEligibilityEnabled: true,
                    serviceEligibilityEnabled: true,
                    npi: "npi",
                },
            ],
            policyIds: ["policyIds", "policyIds"],
            state: "AL",
            messages: ["messages", "messages"],
            clinicalInfo: {
                diagnoses: ["diagnoses", "diagnoses"],
            },
            conditionalPatientResponsibilities: [
                {
                    conditions: [
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                    ],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: {
                            minutes: 1,
                            min: 1,
                            max: 1,
                        },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
                {
                    conditions: [
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                        {
                            diagnoses: ["diagnoses", "diagnoses"],
                        },
                    ],
                    limit: {
                        type: "UNKNOWN",
                        value: 1,
                        metric: "VISIT",
                        period: "ANNUAL",
                        units: {
                            minutes: 1,
                            min: 1,
                            max: 1,
                        },
                    },
                    patientResponsibility: {
                        total: 1,
                        fallback: 1,
                        deductible: 1,
                        deductibleType: "INDIVIDUAL",
                        coinsurance: 1,
                        coinsurancePercent: 1,
                        copayment: 1,
                        oopFallback: 1,
                        oopCopayment: 1,
                        oopCoinsurance: 1,
                        oopDeductible: 1,
                    },
                },
            ],
        });
    });
});
