// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../mock-server/MockServerPool";
import { BridgeApiClient } from "../../../src/Client";

describe("Health", () => {
    test("listHealth Events", async () => {
        const server = mockServerPool.createServer();
        const client = new BridgeApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                { id: "id", status: "HEALTHY", previousStatus: "HEALTHY", eventAt: "2024-01-15T09:30:00Z" },
                { id: "id", status: "HEALTHY", previousStatus: "HEALTHY", eventAt: "2024-01-15T09:30:00Z" },
            ],
            count: 1,
        };
        server
            .mockEndpoint()
            .get("/api/payer-groups/id/health/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payerGroups.health.listHealthEvents("id");
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    status: "HEALTHY",
                    previousStatus: "HEALTHY",
                    eventAt: "2024-01-15T09:30:00Z",
                },
                {
                    id: "id",
                    status: "HEALTHY",
                    previousStatus: "HEALTHY",
                    eventAt: "2024-01-15T09:30:00Z",
                },
            ],
            count: 1,
        });
    });
});
