// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface EstimateChargeCreateV1Response {
    id: string;
    createdAt: string;
    updatedAt: string;
    patientId: string;
    serviceEligibilityId: string;
    externalId?: string;
    amount: number;
    status: BridgeApi.billing.EstimateChargeCreateV1ResponseStatus;
}
