// This file was auto-generated by Fern from our API Definition.

export const EstimateChargesListV1ResponseItemStatus = {
    Pending: "PENDING",
    Authorizing: "AUTHORIZING",
    Authorized: "AUTHORIZED",
    AuthorizationFailed: "AUTHORIZATION_FAILED",
    AuthorizationExpired: "AUTHORIZATION_EXPIRED",
    AuthorizationReleasing: "AUTHORIZATION_RELEASING",
    AuthorizationCancelled: "AUTHORIZATION_CANCELLED",
    Capturing: "CAPTURING",
    Captured: "CAPTURED",
    CapturedBalanceRemaining: "CAPTURED_BALANCE_REMAINING",
    CaptureFailed: "CAPTURE_FAILED",
    Refunding: "REFUNDING",
    Refunded: "REFUNDED",
    RefundFailed: "REFUND_FAILED",
    RefundedBalanceRemaining: "REFUNDED_BALANCE_REMAINING",
    NoCharge: "NO_CHARGE",
} as const;
export type EstimateChargesListV1ResponseItemStatus =
    (typeof EstimateChargesListV1ResponseItemStatus)[keyof typeof EstimateChargesListV1ResponseItemStatus];
