// This file was auto-generated by Fern from our API Definition.

export interface EstimateChargeAuthorizeStripeV1ResponseStripe {
    status?: string;
    client_secret?: string;
    last_payment_error?: unknown;
    next_action?: unknown;
}
