/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentsListV1OrderPaidAt = "asc" | "desc";
export const PaymentsListV1OrderPaidAt = {
    Asc: "asc",
    Desc: "desc",
} as const;
