// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface PaymentsListV1Response {
    /** List results */
    items: BridgeApi.PaymentsListV1ResponseItem[];
    /** Total count (if available) */
    count?: number;
}
