// This file was auto-generated by Fern from our API Definition.

export const PaymentGetV1ResponseType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type PaymentGetV1ResponseType = (typeof PaymentGetV1ResponseType)[keyof typeof PaymentGetV1ResponseType];
