// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../index.js";

export interface PaymentsListV1Response {
    id: string;
    createdAt: string;
    serviceId: string;
    paidAt: string;
    transactionId: string;
    type: BridgeApi.PaymentsListV1ResponseType;
    amount: number;
    externalId?: string;
    memo?: string;
}
