/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentGetV1ResponseType = "PATIENT" | "ADJUSTMENT";
export const PaymentGetV1ResponseType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
