// This file was auto-generated by Fern from our API Definition.

export const PaymentsListV1ResponseType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type PaymentsListV1ResponseType = (typeof PaymentsListV1ResponseType)[keyof typeof PaymentsListV1ResponseType];
