// This file was auto-generated by Fern from our API Definition.

export const PaymentCreateV1ResponseType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type PaymentCreateV1ResponseType =
    (typeof PaymentCreateV1ResponseType)[keyof typeof PaymentCreateV1ResponseType];
