// This file was auto-generated by Fern from our API Definition.

export const PaymentsListV1ResponseItemType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type PaymentsListV1ResponseItemType =
    (typeof PaymentsListV1ResponseItemType)[keyof typeof PaymentsListV1ResponseItemType];
