/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServicePaymentsListV1ResponseType = "PATIENT" | "ADJUSTMENT";
export const ServicePaymentsListV1ResponseType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
