// This file was auto-generated by Fern from our API Definition.

export interface PayerGetV1Response {
    id: string;
    code: string;
    name: string;
    memberId: boolean;
    hint?: string;
}
