/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface ConsentVersionsListV1Response {
    type: BridgeApi.ConsentVersionsListV1ResponseType;
    version: string;
}
