// This file was auto-generated by Fern from our API Definition.

export const ConsentVersionsListV1ResponseType = {
    AssignmentOfBenefits: "ASSIGNMENT_OF_BENEFITS",
    ConsentToTreat: "CONSENT_TO_TREAT",
    PrivacyNotice: "PRIVACY_NOTICE",
} as const;
export type ConsentVersionsListV1ResponseType =
    (typeof ConsentVersionsListV1ResponseType)[keyof typeof ConsentVersionsListV1ResponseType];
