// This file was auto-generated by Fern from our API Definition.

export const ConsentVersionsListV1ResponseItemType = {
    AssignmentOfBenefits: "ASSIGNMENT_OF_BENEFITS",
    ConsentToTreat: "CONSENT_TO_TREAT",
    PrivacyNotice: "PRIVACY_NOTICE",
} as const;
export type ConsentVersionsListV1ResponseItemType =
    (typeof ConsentVersionsListV1ResponseItemType)[keyof typeof ConsentVersionsListV1ResponseItemType];
