/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PatientConsentsListV1Response {
    id: string;
    patientId: string;
    type: BridgeApi.PatientConsentsListV1ResponseType;
    version: string;
    consentedAt: string;
    expiresAt: string;
    status: BridgeApi.PatientConsentsListV1ResponseStatus;
}
