/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientConsentCreateV1ResponseStatus = "ACTIVE" | "EXPIRING_SOON" | "EXPIRED";
export const PatientConsentCreateV1ResponseStatus = {
    Active: "ACTIVE",
    ExpiringSoon: "EXPIRING_SOON",
    Expired: "EXPIRED",
} as const;
