/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PatientConsentCreateV1RequestType = "ASSIGNMENT_OF_BENEFITS" | "CONSENT_TO_TREAT" | "PRIVACY_NOTICE";
export const PatientConsentCreateV1RequestType = {
    AssignmentOfBenefits: "ASSIGNMENT_OF_BENEFITS",
    ConsentToTreat: "CONSENT_TO_TREAT",
    PrivacyNotice: "PRIVACY_NOTICE",
} as const;
