// This file was auto-generated by Fern from our API Definition.

export const PatientConsentCreateV1ResponseStatus = {
    Active: "ACTIVE",
    ExpiringSoon: "EXPIRING_SOON",
    Expired: "EXPIRED",
} as const;
export type PatientConsentCreateV1ResponseStatus =
    (typeof PatientConsentCreateV1ResponseStatus)[keyof typeof PatientConsentCreateV1ResponseStatus];
