/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BridgeApi from "../../../index.js";

export interface PatientConsentCreateV1Request {
    type: BridgeApi.PatientConsentCreateV1RequestType;
    version: string;
    consentedAt: string;
}
