// This file was auto-generated by Fern from our API Definition.

import * as BridgeApi from "../../../../../index.js";

export interface ServicePaymentsListV1ResponseItem {
    id: string;
    createdAt: string;
    serviceId: string;
    paidAt: string;
    transactionId: string;
    type: BridgeApi.services.ServicePaymentsListV1ResponseItemType;
    amount: number;
    externalId?: string;
    memo?: string;
}
