// This file was auto-generated by Fern from our API Definition.

export const ServicePaymentsListV1ResponseItemType = {
    Patient: "PATIENT",
    Adjustment: "ADJUSTMENT",
} as const;
export type ServicePaymentsListV1ResponseItemType =
    (typeof ServicePaymentsListV1ResponseItemType)[keyof typeof ServicePaymentsListV1ResponseItemType];
